### ISSUE TITLE
希望添加鼠标滚轮滚动改变选项

### ISSUE THREAD

**Issue by zxcec** [SchneeHertz/exhentai-manga-manager#101]
现在使用”按名称搜索“进去还需要手动点两次，建议整个软件添加滚轮滚动改变选项

**Comment by SchneeHertz** [comment]
可以具体说明是哪个部分的操作吗？

**Comment by zxcec** [comment]
![屏幕截图 2023-08-16 095824](https://github.com/SchneeHertz/exhentai-manga-manager/assets/51906392/af07c486-656d-4624-aef4-390f1d49ab4a)
![屏幕截图 2023-08-16 095913](https://github.com/SchneeHertz/exhentai-manga-manager/assets/51906392/3f4ce518-0cfc-422c-8f15-4a39659f56ab)
![屏幕截图 2023-08-16 095931](https://github.com/SchneeHertz/exhentai-manga-manager/assets/51906392/90c22db0-c4c4-4739-af02-3f54913de927)
![屏幕截图 2023-08-16 100044](https://github.com/SchneeHertz/exhentai-manga-manager/assets/51906392/43c0419b-5759-483c-9296-69fd5877d7b2)

**Comment by zxcec** [comment]
抱歉，之前点错了。
我希望是用滚轮替代第二步和第三步

**Comment by SchneeHertz** [comment]
下次更新我将exhentai作为这个选择框的默认值并执行一次搜索，滚轮的操作不够直观

**Comment by SchneeHertz** [comment]
1.5.2已更新相关UI
