### ISSUE TITLE
少部分本子使用内建阅读器打开时会一直卡在loading界面

### ISSUE THREAD

**Issue by melon0918** [SchneeHertz/exhentai-manga-manager#104]
![image](https://github.com/SchneeHertz/exhentai-manga-manager/assets/77735556/ac0857c8-287b-497c-8426-0999649e5307)
试了下外置阅读器无此问题
例如：(AC2) [MeltdoWN COmet (Yukiu Con)] Bitch demo Genki nara Sore de Ii [Chinese] [绅士仓库汉化]
https://exhentai.org/g/2018034/6cf16bf79f/
(AC2) [K+W (sasachinn)] Ikazuchi Inazuma-chan x Batsu Game (Kantai Collection -KanColle-) [Chinese] [绅士仓库汉化]
https://exhentai.org/g/1832380/a1361f1f67/

同是jpg格式、顺序从000.jpg开始排的其他本子没有观测到这个问题，猜测是目录名的问题？

**Comment by melon0918** [comment]
应该不是目录名问题···试了下 无论是什么名字都会这样 应该还是图片的问题

**Comment by SchneeHertz** [comment]
出现问题时，按Ctrl+Shift+I打开Devtool，Console是否有显示错误信息，Roaming/exhentai-manga-manager文件夹内的log.txt内是否有显示错误信息？

**Comment by SchneeHertz** [comment]
我在EX用存档下载了这两本，打开都是正常的
"(AC2) [MeltdoWN COmet (雪雨こん)] ビッチでも元気ならそれでいい [中国翻訳].zip"
"(AC2) [K+W (ささちん)] 雷電ちゃん×罰ゲーム (艦隊これくしょん -艦これ-) [中国翻訳].zip"

你可以试一下重新下载，看看是不是文件损坏的问题

**Comment by melon0918** [comment]
console中没有报错，log.txt内有一个报错，但我感觉和这个不相关，因为是在扫描入库时发生的。打开该本，卡在loading时log没有产生新的报错
![image](https://github.com/SchneeHertz/exhentai-manga-manager/assets/77735556/ec6ba13e-c190-4273-ae45-959c2fc2cadb)
![image](https://github.com/SchneeHertz/exhentai-manga-manager/assets/77735556/85b3e5c9-c750-48f7-92f9-5e41799e22a8)
刚刚也试了下重新下载，我也是EX里archive download里选原图下载，honeyview查看是一切正常，但软件内置查看器还是卡在loading，奇怪了···

**Comment by SchneeHertz** [comment]
用终端启动exhentai-manga-manager.exe，观察loading的时候终端有没有报错内容？

**Comment by melon0918** [comment]
有，报错如下：
(node:45080) UnhandledPromiseRejectionWarning: Error: Expected positive integer for width but received 2560.458417534828 of type number
    at Object.invalidParameterError (C:\Users\Menoka\Downloads\Compressed\exhentai-manga-manager.Portable.1.5.1\exhentai-manga-manager Portable 1.5.1\resources\app.asar\node_modules\sharp\lib\is.js:124:10)
    at Sharp.resize (C:\Users\Menoka\Downloads\Compressed\exhentai-manga-manager.Portable.1.5.1\exhentai-manga-manager Portable 1.5.1\resources\app.asar\node_modules\sharp\lib\resize.js:249:18)
    at C:\Users\Menoka\Downloads\Compressed\exhentai-manga-manager.Portable.1.5.1\exhentai-manga-manager Portable 1.5.1\resources\app.asar\index.js:746:14
(Use `exhentai-manga-manager --trace-warnings ...` to show where the warning was created)
(node:45080) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

**Comment by SchneeHertz** [comment]
![image](https://github.com/SchneeHertz/exhentai-manga-manager/assets/39257008/d47ae048-6bfa-4e75-a3b6-5f46015cf682)
临时方案：你改一下这里的设置，填你的屏幕宽度或者其他整数

这个bug我下个版本会修

**Comment by melon0918** [comment]
好的，感谢
