### ISSUE TITLE
能否加入漫画详情页面的，下一篇功能

### ISSUE THREAD

**Issue by tianhefanxing** [SchneeHertz/exhentai-manga-manager#105]
非常感谢作者，能够制作如此好用的软件，本小白对大佬表示敬意！
----------------------------------------------------------------------------------------
  现在详情页面似乎无法进行下一本的跳转，能否在详情页面（不是内置阅读器页面）加入，下一本功能？

  使用方向左或者方向右，在详情页面快速的跳转到当前顺序下的下一本漫画，这样可以快速的查漫画的基本信息，做到对本子的信息，进行检查和修正。

例如：
  这是通过第三方下载器下载的漫画，一般情况下页数与大小一致是对的，但是它的大小与原大小不一致。

随后检查发现是有图片未下载完全的情况

因此如果有下一篇的功能，检查起来就会很方便。

**Comment by tianhefanxing** [comment]
第二张放错了
<img width="960" alt="屏幕截图 2023-08-29 172559" src="https://github.com/SchneeHertz/exhentai-manga-manager/assets/110874890/6b69e969-0ae8-499c-8d62-3aa7888f5a54">

**Comment by SchneeHertz** [comment]
这个功能下个版本会加上
PS: 打下码吧朋友

**Comment by tianhefanxing** [comment]
好的，好的
抱歉了大佬下次注意

**Comment by SchneeHertz** [comment]
1.5.3已更新相关功能
