### ISSUE TITLE
HDoujin Metadata Support

### ISSUE THREAD

**Issue by arisune** [SchneeHertz/exhentai-manga-manager#115]
Hey, love your software, has great potential!

Just found it the other day and already liking it a lot.
I have a rather large collection that I download with HDoujin Downloader,
I'm sure you're familiar with it, all my archives have the saved metadata as info.json in them,
it would be awesome if exhentai-manga-manager could read those files and import that metadata. Or at least the e/xhentai URLs inside them would be great.

kind regards,
ari

**Comment by SchneeHertz** [comment]
Thank you for your feedback. However, I currently have no plans to support metadata files from third-party download software. You can refer to step 5 in https://github.com/SchneeHertz/exhentai-manga-manager/wiki/English-Instruction#library to download a backup of the E-hentai gallery data before July 30, 2023, and import it into the software. This should address most of your metadata retrieval needs.
