### ISSUE TITLE
想请教一下数据库中的hash是如何生成的

### ISSUE THREAD

**Issue by dudulu23** [SchneeHertz/exhentai-manga-manager#119]
想请教一下database数据库中的hash id  coverhash这几项是如何生成的，如果我直接在数据库里添加数据，在软件里会不会直接显示这本漫画

**Comment by SchneeHertz** [comment]
id是随机字符串
coverhash就是第一张图片的sha1值
hash分情况，如果图片数量大于8，取第8张图片的sha1，如果小于8，与coverhash相同
