### ISSUE TITLE
如果作者有余力的话推荐支持doujinshi.org

### ISSUE THREAD

**Issue by vansto** [SchneeHertz/exhentai-manga-manager#12]
现在eh有很多版权删除的本子都搜不到了,doujinshi只有标签信息应该是不构成版权问题的

**Comment by SchneeHertz** [comment]
> 现在eh有很多版权删除的本子都搜不到了,doujinshi只有标签信息应该是不构成版权问题的

这个网站的API的次数限制很严格，每天只能请求50次，而且没有包括汉化的漫画，目前不考虑支持
