### ISSUE TITLE
漫画页数显示问题

### ISSUE THREAD

**Issue by dudulu23** [SchneeHertz/exhentai-manga-manager#120]
一本漫画被扫描一次后页数就固定了，如果我想从中添加新页或删除一页后界面上的页数没有改变，只能通过修补本地元数据重新扫一遍，漫画数量一多重扫很花时间，我想可以添加右键修补单本漫画的数据功能，或者点击漫画后会自动更新页数

**Comment by SchneeHertz** [comment]
已更新
