### ISSUE TITLE
A couple of suggestions for adding new files.

### ISSUE THREAD

**Issue by VanTuz5** [SchneeHertz/exhentai-manga-manager#124]
I organize my manga into folders to make it easier to find later. Because of this, the following proposal appeared - to scan a separate folder so that the program can quickly find new manga.
And the second suggestion is to drag'n'drop the manga file to the program window so that the file can be added to the collection.

**Comment by SchneeHertz** [comment]
@VanTuz5 Even with a full library scan, the software only processes files that have not been scanned before, so there is no difference in speed between scanning individual modified folders and scanning the entire library.
Is "collection" the collection unit in the software? It has a separate organizing interface. Anyway, I don't want to add too much file management functionality in the software. When designing this software, I hope it has less intrusiveness and maintains the original state of the library without changing it.
If you need file management, please do so in the file manager.

**Comment by VanTuz5** [comment]
It happens that I download a manga that is still ongoing, and when it comes out completely, for the sake of it I have to rescan everything, and this is more than 6,000 files, and this takes time. That's why I wish there was a way to do everything faster. Or it would be cool to indicate that the file name has changed, since you don't want to consider my scanning suggestions.

**Comment by SchneeHertz** [comment]
There is a "Rescan" function button on the details page of the comic that can re-scan the current comic. I think this can meet most of the scene requirements.

**Comment by VanTuz5** [comment]
If the file has a slightly different name, for example, there was a postscript (ongoing) and it became (complete), then the program will not see this file and everything will have to be rescanned. But if it were possible to indicate that the file name is now such and such, then there would be no need to do this.
