### ISSUE TITLE
批量获取原数据功能的默认的获取路径可以改成KEY或者提供选项吗

### ISSUE THREAD

**Issue by sqsq37** [SchneeHertz/exhentai-manga-manager#128]
原因我现在好多漫画我是自己机翻修改后才丢到文件夹里的，
图片已经和默认下下来的不一样了
但是文件夹漫画名还是一样了
批量获取元数据的sha1获取基本识别不了我机翻修改过的封面
但是key获取方式可以，所以每一本都要手动搜索获取元数据

**Comment by SchneeHertz** [comment]
可以考虑加一个选项，我最近看下有没有时间加
不过通过文件名搜索到对应的漫画成功率挺低的，因为文件名通常会有一些前缀和后缀，不手动删掉这些文本的话搜不到对应的漫画

**Comment by SchneeHertz** [comment]
已更新
