### ISSUE TITLE
npm run dev 后浏览器给出的界面点击设置没有反应

### ISSUE THREAD

**Issue by semiconducto** [SchneeHertz/exhentai-manga-manager#129]
具体来说，我要如何在设置里选择库文件夹呢？请问作者点击设置图标没有反应的原因可能是什么？
![屏幕截图 2024-02-06 005914](https://github.com/SchneeHertz/exhentai-manga-manager/assets/96565662/cdbdb1db-8f20-47c3-a55d-678fa7a9c2a4)

**Comment by SchneeHertz** [comment]
这是个electron应用，你需要再开一个终端运行npm run start
