### ISSUE TITLE
希望增加多选功能，可以选定多个作品批量获取元数据或者改变tag

### ISSUE THREAD

**Issue by RanAronX** [SchneeHertz/exhentai-manga-manager#131]
问题背景：
在网络链接不稳定的情况下，部分有元数据作品在获取元数据时会被标记为“tag-failed”，因此需要手动再获取一遍
针对这种情况，一般要将tag-failed的作品重新获取一遍
但是目前批量获取元数据的方式只有默认顺序获取，新导入库的tag-failed的作品是排在最后的，而EX本身对拉取元数据的行为也有限制，单次拉取大概500本就会被ban。
也就是说，当本地存在超过500本的tag-failed作品时，选中“同时批量获取tag-failed漫画的元数据”这一选项来对tag-failed作品二次拉取元数据，永远只有前500本能被再次拉取，然后账号就会被ban，后面的作品还是只能手动一个一个去拉取。
我个人本地有近万本作品，其中tag-failed的作品超过2000，每一个都手动再去二次确认是非常不实际的。

功能建议：
希望增加多选功能，可以让我批量选中特定范围的作品来再次获取元数据。
按照目前的获取逻辑来说，一旦你的本地有过500本的tag-failed作品，而且你开启批量获取tag-failed漫画的元数据这一选项，那么你永远都是在tag-failed的默认前500个作品里循环，这是非常不合理的

**Comment by RanAronX** [comment]
关于EX拉取：
虽然官方没有明确表示拉取数据也会超额，但是实际情况是也会被ban，我认为这是因为拉取数据的时候也会产生流量导致的。我个人通过多个EX权限账号多次试验，大概确定单次获取超额的数量在500次左右。

由于账号一旦被ban，下次再重新拉取元数据又要从头开始，因此会出现反复拉取，直到默认排序的前500本里全部都是真正的tag-failed作品时，后面的作品就再也没有机会被批量拉取了

**Comment by SchneeHertz** [comment]
> 关于EX拉取： 虽然官方没有明确表示拉取数据也会超额，但是实际情况是也会被ban，我认为这是因为拉取数据的时候也会产生流量导致的。我个人通过多个EX权限账号多次试验，大概确定单次获取超额的数量在500次左右。
> 
> 由于账号一旦被ban，下次再重新拉取元数据又要从头开始，因此会出现反复拉取，直到默认排序的前500本里全部都是真正的tag-failed作品时，后面的作品就再也没有机会被批量拉取了

”IP address has been temporarily banned“错误会导致获取中断而且最后获取失败的漫画被标记为non-tag状态，tag-failed是因为ex数据库上找不到对应的漫画

获取tag-failed漫画这个选项不适用于IP ban的情况

总之建议你先下载dump的数据库导入后再使用批量获取，基本就可以解决问题了
