### ISSUE TITLE
1.5.14使用文件夹名当作标题出现错误

### ISSUE THREAD

**Issue by universc** [SchneeHertz/exhentai-manga-manager#133]
在使用文件夹名当作标题时会出现显示不完全的错误

![QQ截图20240405232038](https://github.com/SchneeHertz/exhentai-manga-manager/assets/134767996/d76e9dc5-d29f-4d51-87f1-de39b32c390b)
![QQ截图20240405231941](https://github.com/SchneeHertz/exhentai-manga-manager/assets/134767996/d5aa8fb2-abfd-4137-9bd0-5190eb32e70e)

**Comment by SchneeHertz** [comment]
返回文件名的方法有bug，下个版本会修复

**Comment by SchneeHertz** [comment]
1.5.15已更新
