### ISSUE TITLE
希望可以通过web访问电脑上的漫画库

### ISSUE THREAD

**Issue by njjzx** [SchneeHertz/exhentai-manga-manager#135]
目前在电脑上进行漫画整理，但是看漫画大部分时候还是用移动设备居多

希望能在局域网内，通过访问IP+端口的方式，浏览已经整理好的漫画

类似jellyfin或者komga那样的形式。使用perfect viewer确实可以看漫画，但是缺少标签，当漫画数量达到16000+，按作者整理，文件夹也有1800+的时候，还是希望能通过已经整理好的标签来看相关的漫画

**Comment by SchneeHertz** [comment]
移动端的webview工作量挺大的，没有在计划里面

**Comment by KazeLiu** [comment]
> 移动端的webview工作量挺大的，没有在计划里面

我这边想要个PC端的页面，这个可以做吗？我软件是放在服务器上的，我用电脑比手机多

**Comment by SchneeHertz** [comment]
> > 移动端的webview工作量挺大的，没有在计划里面
> 
> 我这边想要个PC端的页面，这个可以做吗？我软件是放在服务器上的，我用电脑比手机多

Browser/Server架构可以用Lanraragi，这个软件定位是桌面软件
