### ISSUE TITLE
1.5.14版本手动选择作者标签卡顿

### ISSUE THREAD

**Issue by njjzx** [SchneeHertz/exhentai-manga-manager#136]
由于版权原因，ex清理了所有鳄鱼社的杂志短篇，所以这些漫画获取不到元数据。我尝试手动给每个短篇标注作者，但是非常卡顿，基本上ctrl+c之后需要等待20秒以上，退出漫画详情页到海报墙又要等待20秒

我的电脑配置是5800X+4070 ti，64G内存，出现问题时，CPU和内存占用均小于40%。库文件夹位于机械硬盘，元数据存放目录使用的是默认文件夹，位于固态硬盘

**Comment by SchneeHertz** [comment]
可以用其他的元数据源, Hentag可以通过标题匹配到ex的数据，也包括被删除的漫画

ctrl+c是哪个操作，可以详细说吗
退出详情页不应该有延迟的，本质只是关掉上层的窗口

**Comment by njjzx** [comment]
就是简单的把标题里的作者名复制到artist栏。我今天又测试了一下，实际上不需要复制动作，只是点击artist栏想输入，就会卡住

操作流程是 漫画详情页-编辑标签-artist，然后卡住

我也测试了是否和压缩包有关。测试结果为，无论源文件是zip压缩包还是文件夹，在artist上都会卡住超过20秒

至于说元数据，比如说这一本，(漢化組漢化組×Foxglove#41) [火鳥] 快楽ヒストリエ ～古代ローマ編～ (COMIC 快楽天ビースト 2017年1月号).zip，在哪个元数据源都匹配不到ex的数据。当初ex官方清理过一大批鳄鱼社的杂志短篇，这些数据现在都查不到了

**Comment by SchneeHertz** [comment]
编辑标签部分的性能和库内漫画的量，标签的量都有关系，因为标签的选项是在切换编辑模式时生成的，如果没有必要，进入编辑模式后没有完成前不要退出，编辑模式在切换漫画时会保持。
不过这个应该和你反馈的问题不完全是同一个问题

选择标签的部分有个性能问题，我修改代码进行了优化，不过要月底才会release

**Comment by njjzx** [comment]
好的，多谢。有新的release我会第一时间换上的。

另外我测试了一下，如果使用剪贴板粘贴标签信息的方式，就不会有卡顿，我现在先用这个方式添加tag吧

**Comment by SchneeHertz** [comment]
1.5.15已更新
