### ISSUE TITLE
希望能增加通过网址获取tag的范围

### ISSUE THREAD

**Issue by njjzx** [SchneeHertz/exhentai-manga-manager#137]
由于fakku和irodori的版权要求，EX彻底删除了很多杂志短篇还有部分作者的所有商业漫画。不过在有些网站还是能够获取到tag的

比如这一本 [Kuroana you & 立花オミナ] Royal Beauty and luxury 4P! 8p! 12p
无论是在exhentai还是chaikai都搜不到，但是可以在hitomi找到：
https://hitomi.la/manga/isekai-harem-monogatari-2-~oukyuu-bijo-tachi-to-gouka-4p!-8p!-12p!~-%E4%B8%AD%E6%96%87-2346850.html#1

还有就是，有一些漫画，在fakku上有收录，但是在chaika的archive里没有，或者是archive里没有但是gallery里有，这些tag都没办法自动获取，需要复制下来通过粘贴板才能整理到标签。

如果可以的话，希望能添加对这几个网站（hitomi/fakku/chaika-gallery）的tag支持。如果手动获取元数据的搜索栏添加工作量较大或者不可行的话，希望在手动编辑标签里，可以通过手动添加网址的方式，获取tag

**Comment by DeathPayner** [comment]
hitomi只能说是备选网站，hentag是可以正常搜到你发的这本EX链接的，这个问题严格来说不算问题，hitomi标签也是扒的EX。只能说hentag配合chaika没有搜不到的版权本

**Comment by njjzx** [comment]
看来是我之前只使用了日语搜索，所以没搜到。不过对于2012年之前的快乐天的短篇，这俩能覆盖全吗？类似[Hamao]Lover's Concerto(COMIC Kairakuten Beast 2012-10)这种我是真的搜不到，是我的搜索方式有问题？
