### ISSUE TITLE
执行手动扫描时报错：load *** failed because SequelizeDatabaseError: SQLITE_ERROR: no such column: hiddenBook

### ISSUE THREAD

**Issue by Nigel-NI** [SchneeHertz/exhentai-manga-manager#138]
**Before giving feedback on a bug, please make sure that what you are giving feedback on is not explained in the wiki**
**在提供错误反馈之前，请确保您所反馈的内容在wiki中没有解释。**

**Describe the bug**
**描述错误**
按照wiki的说明，选择库文件夹，并点击手动扫描后弹出大量弹窗，如下图所示。

**Log**
**错误日志**
```
start loading library
load 200 book from library
load E:\Aa\b\1.1\1.zip failed because SequelizeDatabaseError: SQLITE_ERROR: no such column: hiddenBook, 1 of 200
……
load E:\Aa\b\1.1\200.zip failed because SequelizeDatabaseError: SQLITE_ERROR: no such column: hiddenBook, 200 of 200
```

**Screenshots**
**截图**
![image](https://github.com/SchneeHertz/exhentai-manga-manager/assets/23294384/9a2d381e-a0fb-4124-9017-91335798202f)

**Additional context**
**附加信息**
暂无

**Comment by SchneeHertz** [comment]
在1.5.12中有一个补丁修复了旧数据库中hiddenBook未生效的问题，之后的版本为了优化性能，移除了该补丁，你可以从以下方式二选一来修复这个问题：
- 安装1.5.12版本，进行手动扫描应用补丁，再安装最新版本
- 在备份元数据后关闭软件，删除Roaming文件夹中的database.sqlite，再进行手动扫描
