### ISSUE TITLE
希望能在搜索作者名时追加完全匹配的选项

### ISSUE THREAD

**Issue by loliconyue** [SchneeHertz/exhentai-manga-manager#140]
在搜索一些名字比较短的作者时，会将名字中包含该作者名的其他作者一同搜索出来
如搜索作者a:"aka"时，会显示出“akagi kuro”，"akazawa red"等作者的作品

**Comment by SchneeHertz** [comment]
应该会参考ehentai用$结尾的方式

**Comment by SchneeHertz** [comment]
更新1.5.16，已增加该功能
