### ISSUE TITLE
作者有考虑过制作Linux版或者Docker版吗

### ISSUE THREAD

**Issue by luoli233** [SchneeHertz/exhentai-manga-manager#143]
功能和界面都不错，真的很希望能有Linux版或者Docker版可以进行远程观看、管理

**Comment by SchneeHertz** [comment]
这个软件是桌面软件，目前没有通过网络在另一台机器上运行的功能，也没有计划增加这个功能。
Linux版如果有linux的开发者参与测试应该不难，功能大部分都是平台无关的。
