### ISSUE TITLE
自动输入的搜索关键词会截掉小数点后的文字

### ISSUE THREAD

**Issue by loliconyue** [SchneeHertz/exhentai-manga-manager#144]
首先感谢您追加了搜索时完全匹配的功能。

目前在使用过程中还遇到了一个问题。
在手动获取元数据的时候，搜索框里会自动切掉小数点后面的文字。
在sha1模式无法搜索到结果时，采用keyword搜索时需要每次手动复制标题

如原文件名”(COMIC1☆15) [C.Rs NEST (しーあーる)] 鈴谷のここ、空いてますよ (アズールレーン) [中国翻訳]“，
搜索框中默认输入的检索关键词为”(COMIC1☆15) [C“

![QQ截图20240616193451](https://github.com/SchneeHertz/exhentai-manga-manager/assets/39231806/c296e31e-f75a-4634-a18a-df12cca7d1fa)

**Comment by SchneeHertz** [comment]
是处理文件名后缀时的问题，下个版本会修复
