### ISSUE TITLE
请求加长标签框的显示的标签个数

### ISSUE THREAD

**Issue by HPFAIZ** [SchneeHertz/exhentai-manga-manager#145]
我没有使用导入标签
我是自己添加的标签，但是标签长度太短每次看到的标签数量有限
如图所示，每次只能看到5个标签，向下滚动添加标签很麻烦
请求大大加长标签页可显示的标签个数
![微信图片_20240617194918](https://github.com/SchneeHertz/exhentai-manga-manager/assets/134574334/185a3d43-29de-4b46-9b38-7f77f01d0b85)

**Comment by SchneeHertz** [comment]
可以，下个版本调整一下

**Comment by HPFAIZ** [comment]
感谢！
