### ISSUE TITLE
请求添加元数据页数与文件夹内实际页数比较的功能

### ISSUE THREAD

**Issue by loliconyue** [SchneeHertz/exhentai-manga-manager#146]
整理本子时，一些扫描下来的元数据会存在与实际本子不匹配的情况。
部分本子会被扫到总集篇，或者同人cg被扫到作者的合集图集中
![image](https://github.com/SchneeHertz/exhentai-manga-manager/assets/39231806/2cd58119-4052-4beb-a241-6a952c5a2f9a)

目前手动整理下来，觉得可以通过比较页数的方式来进行大致判断。
因此希望能够增加一个选项来筛选出页数不匹配的本子

考虑到有人会手动删除文件内的广告页，能够手动设置页数差也许是一个思路

**Comment by SchneeHertz** [comment]
可以，我考虑下怎么加
