### ISSUE TITLE
希望可以配置一个专用文件夹进行扫描增加到库，然后将扫描内容移动到主目录对应路径

### ISSUE THREAD

**Issue by evdua** [SchneeHertz/exhentai-manga-manager#147]
**Is your feature request related to a problem? Please describe.**
**您的功能请求是否与问题有关？请描述一下。**
A clear and concise description of what the problem is. 
对问题是什么的清晰简明描述。

答：漫画过多，扫描时间长

**Describe the solution you'd like**
**描述您想要的解决方案**
对您希望发生的事情进行清晰简明的描述。

答：新增配置一个文件夹专门用于扫描，与主文件夹一一对应，然后将扫描的内容文件或文件夹移动到主目录对应路径

**Describe alternatives you've considered**
**描述您考虑过的替代方案**
对任何替代解决方案或特性进行清晰简明的描述。

答：无，添加一本，只能全部重新扫描

**Additional context**
**附加上下文**
在这里添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by SchneeHertz** [comment]
扫描到已入库的漫画会跳过后续的步骤，对于以压缩包为存储形式的漫画，已存在的漫画不太会影响扫描的速度，除非量实在很大(100K级别)。
文件夹为存储形式的取决于磁盘性能，这方面没有做太多优化。

对于一般的使用场景，不能预设只有部分文件夹会有变动，所以后续思路应该还是优化扫描的方式。

**Comment by evdua** [comment]
谢谢回答
