### ISSUE TITLE
文件删除有关问题

### ISSUE THREAD

**Issue by rikkajiang** [SchneeHertz/exhentai-manga-manager#149]
出现问题描述：对漫画库的文件右键选择删除文件之后，在弹出确认按钮之前文件就会被删除，经重启重新搜索漫画库之后确认该漫画文件被删除
问题出现软件版本：1.5.17
尝试的措施：重启软件，重启电脑，问题仍然可复现
问题每次均可复现

**Comment by rikkajiang** [comment]
已确认跳过删除确认开关为关闭状态，已尝试重新开关该按钮，仍然无效

**Comment by SchneeHertz** [comment]
确实有这个问题，已经定位到原因，下个版本修复
