### ISSUE TITLE
希望添加 cbz 等漫画压缩格式的支持

### ISSUE THREAD

**Issue by Boycottangent** [SchneeHertz/exhentai-manga-manager#15]
我在本地上对漫画压缩包和一般压缩文件做了格式区隔，漫画压缩包用cbz等格式，有专门的读取软件。但发现 exhentai-manga-manager 目前好像不支持，所以库里的这类文件都无法被识别

**Comment by SchneeHertz** [comment]
我用谷歌搜索了之后发现cbz只是zip文件修改了后缀，如果确实如此且没有兼容问题的话，下个版本我把cbz加入到扫描的范围内

**Comment by Boycottangent** [comment]
> 我用谷歌搜索了之后发现cbz只是zip文件修改了后缀，如果确实如此且没有兼容问题的话，下个版本我把cbz加入到扫描的范围内

是的，还有cb7和cbr，对应7z和rar

**Comment by SchneeHertz** [comment]
@Boycottangent 1.3.11已包含cbz，cbr和cb7的支持
