### ISSUE TITLE
使用反馈与功能请求

### ISSUE THREAD

**Issue by loliconyue** [SchneeHertz/exhentai-manga-manager#151]
1.希望在不填写外置阅读器路径时，点击阅读的“阅”也能打开内置阅读器
2.上个版本新增的功能“增加首页随机标签及快速搜索”，希望能加一个是否显示的开关。或者能够支持自定义快速搜索标签。
3.每页显示的本子数量目前只能选择24，42，72，500，5000。希望能加回每页12本的选项
4.部分本子，ex已经删除了，但是扫面时会匹配到了其他本子。希望能添加一下，删除本子元数据的功能

5.从其他网站下载的本子，修改成和ex上相同的标题，但是用keyword模式无法搜索到。请问这是正常情况吗？

例如：キモメンでも巨根なら名門校のお嬢様を専用孕まセレブビッチにできる
![image](https://github.com/user-attachments/assets/f5e3687f-7e6a-430e-bf6f-f19c2774c51e)
![image](https://github.com/user-attachments/assets/0fc7d8ef-c737-473e-a239-301944eeb951)

**Comment by SchneeHertz** [comment]
1. 可以
2. 可以，我会加一个关闭这个功能的开关
3. 可以
4. 可以加一个移除元数据的功能
5. ex的搜索是偶尔会出现一些异常，原因未明

**Comment by loliconyue** [comment]
感谢大佬回复
还有两点在今天使用的时候意识到了
1.批量获取元数据的过程中希望能加个手动中断的功能，有些时候爬不动总要关掉主程序
2.希望能够添加一下，手动获取元数据的快捷键

**Comment by SchneeHertz** [comment]
> 感谢大佬回复 还有两点在今天使用的时候意识到了 1.批量获取元数据的过程中希望能加个手动中断的功能，有些时候爬不动总要关掉主程序 2.希望能够添加一下，手动获取元数据的快捷键

中断获取可以
使用快捷键手动获取元数据感觉不是常见的场景，不考虑加
