### ISSUE TITLE
希望能添加标签分析能显示的标签数量

### ISSUE THREAD

**Issue by StirrerCymbal5zn** [SchneeHertz/exhentai-manga-manager#152]
我的库有300个左右，想通过标签分析统计的最多标签来应用eh的订阅功能，但是能显示在标签分析树上就只有30个左右。能否多显示一些，我好列入统计。比如库中有5个以上标签就可显示在分析树上，或提供自定义功能。感谢

**Comment by SchneeHertz** [comment]
标签分析的图不容易调整，过段时间我会改那部分的界面，所以近期不做修改

如果要分析数据，可以直接到配置文件夹读数据库，用python脚本之类的分析
