### ISSUE TITLE
能不能增加手动添加标签库功能

### ISSUE THREAD

**Issue by Xh-xie** [SchneeHertz/exhentai-manga-manager#155]
**1.目前软件对于未能获取元数据的漫画，可以手动添加标签，但是标签库（姑且这么说吧）不能手动添加，要么导入api_dump.sqlite库，要么只能用其他联网获取过元数据的漫画标签，很不方便。如图所示。
2.能不能多支持一下pdf格式文件**
![image](https://github.com/user-attachments/assets/355d3172-661f-4fc5-bc70-6c3bf5ffb3ee)
之前我只获取了一个漫画的元数据，然后在为一个只能手动添加标签的漫画编辑标签时，他语言这栏只有“汉语”“翻译”可选，如果我想添加一个“国际语”呢？
尤其是没有这个功能，添加类别这个功能形同虚设，如图。
![image](https://github.com/user-attachments/assets/32296211-1ddb-408a-b0ef-ab5f7711d113)
我既然要添加类别，那说明这个类别肯定是exhentai没有的标签类别，结果这个类别内不能添加任何标签……
![image](https://github.com/user-attachments/assets/ab50e34b-b7ff-4281-af2a-31d2140be00c)

**建议添加一个标签库编辑功能。类似管理合集功能，如图**
![image](https://github.com/user-attachments/assets/585a481a-02f5-42bf-8051-126892c6c01a)

**推荐参考一个名叫Document TagExplorer V5.9.0.2「文件标签和备注管理工具]的软件**
这个软件专门为各类文件加标签，他的标签可以自由建立。
![image](https://github.com/user-attachments/assets/7aecec70-71fa-4f3f-bad5-8301e793b06c)
同时可以标签树可以导出导入。
![image](https://github.com/user-attachments/assets/72b082e6-8c6d-43ad-bc14-ddd03755d494)
导出形式如图。
![image](https://github.com/user-attachments/assets/df35e9fe-39a0-477a-b807-43a234f2066e)
这个软件还可以导出所有打过标签文件的标签txt，比较复杂。软件网址：http://dangerace.ysepan.com/

**最后非常感谢开发此软件，为松鼠党提供了一个很好的管理漫画的软件。**

**Comment by SchneeHertz** [comment]
标签只要输入就能添加
pdf暂时还不考虑支持，这个软件主要还是和exhentai的资源关联的
