### ISSUE TITLE
请问为什么删了panda.chaika的TAG元数据获取，现在好多版权本的元数据只有上面有

### ISSUE THREAD

**Issue by sqsq37** [SchneeHertz/exhentai-manga-manager#160]
RT
hentag上的也没有，因为hentag也是从ex扒的，但是有些新的版权本一开始就不会上传到EX，所以hentag也没有

**Comment by SchneeHertz** [comment]
chaika使用的tag和ex的有些差异，一起使用时使搜索和显示tag显得混乱
而且我觉得使用频率非常低，没有必要继续维护这个功能

**Comment by bennyz327** [comment]
看到功能被刪除我也感到蠻可惜的，一開始提 featrue #78 的用意，也是為了補全被版權下架的書籍的數據缺失

**Comment by SchneeHertz** [comment]
> 看到功能被刪除我也感到蠻可惜的，一開始提 featrue #78 的用意，也是為了補全被版權下架的書籍的數據缺失

chaika也不收录汉化的版权本，raw的版权收录也不齐，不知道有什么存在意义。我用下来感觉就是一点用都没
