### ISSUE TITLE
问一下，支持CBZ格式和元数据写入吗？

### ISSUE THREAD

**Issue by X012C** [SchneeHertz/exhentai-manga-manager#164]
如题。

**Comment by SchneeHertz** [comment]
cbz支持读取，不支持元数据写入压缩包的功能

**Comment by X012C** [comment]
> cbz支持读取，不支持元数据写入压缩包的功能

~~感觉转圈好久都没有看到成功加载到文件进去。~~

元数据写入后续会考虑加吗？多设备使用的，标签数据同步也很重要。

**Comment by SchneeHertz** [comment]
有单独的元数据数据库文件，默认在%AppData%\exhentai-manga-manager\metadata.sqlite，同步这个文件就行

**Comment by X012C** [comment]
> 有单独的元数据数据库文件，默认在%AppData%\exhentai-manga-manager\metadata.sqlite，同步这个文件就行

这个是用在Windows之间同步吧。

除了Windows常用设备之外，其他设备可能还是其他操作系统更多，例如移动端（安卓、iOS或者墨水屏封闭系统这类）或者docker这类，支持元数据写入可以让文件能够更加自由流转。

~~如果作者大佬没有这样的使用需求和计划，那就打扰了。 ~~

**Comment by SchneeHertz** [comment]
目前没有计划
