### ISSUE TITLE
开机启动后，最小化后台运行。

### ISSUE THREAD

**Issue by X012C** [SchneeHertz/exhentai-manga-manager#165]
挂LAN服务需求吧，防止社死需要开机初次启动时静默后台运行。样式类似：
![image](https://github.com/user-attachments/assets/5a630162-3a8c-4739-a008-cb6b66718394)
![image](https://github.com/user-attachments/assets/5fc71d8a-33e0-4a52-a351-9995adaee227)

希望能够实现吧。

**Comment by SchneeHertz** [comment]
不是很迫切的功能，之后可能会加
如果有必要的话，请在安全的场景下使用

**Comment by X012C** [comment]
> 不是很迫切的功能，之后可能会加
> 如果有必要的话，请在安全的场景下使用

期待。
