### ISSUE TITLE
请问如何手动更新api_dump.sqlite

### ISSUE THREAD

**Issue by yu45020** [SchneeHertz/exhentai-manga-manager#166]
请问如何获得tag的数据库？ 我搜了一轮没找到法子，只在论坛里找到很久的metadata dump。 

能分享输出api_dump.sqlite 的代码？ 我想每隔一段时间就批量更新，导入新文件的时候就不用再从论坛上逐个抓取。 

这软件很好用，谢谢。

**Comment by SchneeHertz** [comment]
api_dump.sqlite是nyaa的一位用户不定期发布的e-hentai抓取结果存档，可以在https://sukebei.nyaa.si/user/gipaf23445页找到最新的

**Comment by yu45020** [comment]
😅还以为是你写的。
