### ISSUE TITLE
希望软件能适配Windows7电脑系统

### ISSUE THREAD

**Issue by 4399LX** [SchneeHertz/exhentai-manga-manager#167]
希望软件能适配Windows7电脑系统

**描述错误**
安装之后运行软件，提示【无法定位程序输入点 DiscardVirtualMemory 于动态链接库 KERNEL32.dll 上】。

我查了很多，发现[原因](https://www.bilibili.com/read/cv26105163 )是 KERNEL32.dll 的这个DLL最低受支持客户端为windows8，也就是软件最好用Windows10来打开。

因此希望我的渣电脑能用Windows7来玩这个软件。/(ㄒoㄒ)/~~

**Comment by SchneeHertz** [comment]
之前electron有个高危漏洞，只有在不再支持win7的版本上得到了修复。
如果你清楚这个风险，可以使用1.5.5及之前的版本
