### ISSUE TITLE
请问database.sqlite 和metadata.sqlite是调用了cache来更新吗？

### ISSUE THREAD

**Issue by yu45020** [SchneeHertz/exhentai-manga-manager#168]
手动更新文件的tag后并没有直接在这2个数据库内有即使更新，但点开阅读后就更新了。

我不熟悉Vue，但在读代码的时候沿着image viewer找，发现每次阅读文件的时候调用 `saveSetting`, 然后找到 `setting.value`。这应该储存了tag，并且应该是存在某地cache里，可惜我找不到了，请指教。 

api_dump的文件似乎之后调用api拿数据，chaika的数据好拿一点。 我写了些python代码，打算手动批量更新tag。目前用hash的方法很好，但我大多数文件的图片都调过大小和重新压缩。目前用文件名配对数据似乎是捷径。

**Comment by SchneeHertz** [comment]
漫画数据的保存操作是调用了saveBook方法
https://github.com/SchneeHertz/exhentai-manga-manager/blob/5d385e690a816076cc7965bfe9480f1fdc8452ca/src/App.vue#L1252
对应主进程的
https://github.com/SchneeHertz/exhentai-manga-manager/blob/5d385e690a816076cc7965bfe9480f1fdc8452ca/index.js#L465

你可以直接将数据写入database.sqlite和metadata.sqlite，只要格式正确就行

**Comment by yu45020** [comment]
还是更新不了😅

我按着 `database.sqlite`里的格式直接更行tag，打开软件后文件没有更新。点阅读后数据库内 readcount 加1，然后tag变回默认值。更新了 `metadata.sqlite` 对应的数据也没用。

请问应该怎么做？

**Comment by SchneeHertz** [comment]
两个数据库都写入肯定是没问题的，你再调试下

**Comment by yu45020** [comment]
弄明白了，确实可以。 写下过程希望对其他人有帮助。 

如何“手动”批量根据文件名更新tag 

1. 假设能从论坛或其他数据源拿到tag，整理到跟 `api_dump.sqlite` 相同格式。 
2. 假设文件名都没有改过
3. 把文件名 (title, title_jpn, token里的) 和对应的 `gid` 存到内存 
4a. Python 的解法是存成 `{'title':[gid], ...}` 一般是一文件名对1个或多个gid。 起了tag外可以取第一个，tag可以合并多个 `gid`的数据。内存足够的话配对10K文件名还是很快的。（从2.08G 的 `api_dump.sqlite` 拿的话大约占2.3G 内存)
4b. 如果要配对的文件少，可以直接`query` 数据库
5. 写入 `database.sqlite` 和 `metadata.sqlite`。 我用免安装版，`database.sqlite` 在根目录，`metadata.sqlite`在`cache`写。注意，根目录下有一样的文件，那个是不对的 😅 。 注意对其格式。 
    a. 先从 `database.sqlite` 拿 `hash`, `filecount`, `posted`, 更新 `tag`, 改 `status` 到 `tagged`。 用 `hash`在`metadata.sqlite`找对应的行并更新数据，错误的数据库的话对应`hash`会不存在
    b. 软件里更新库(Manual Scan)就可以了。
