### ISSUE TITLE
无法设置封面

### ISSUE THREAD

**Issue by ewrtvxc** [SchneeHertz/exhentai-manga-manager#171]
版本1.61和1.62，便携版
指定封面会使封面变成空白，无法使用内置阅读器，重启后恢复
错误信息
Error: An object could not be cloned.
GET file:/exhentai-manga-manager%20portable%201.4.8/resources/app.asar/dist/[object%20Promise] net::ERR_FILE_NOT_FOUND
新功能内置阅读器只显示封面用的不习惯，很多本子第二页才是封面，能不能把新功能改成可选

**Comment by SchneeHertz** [comment]
指定封面的问题已定位到，下个版本修复
只显示封面指的是什么？

**Comment by SchneeHertz** [comment]
可以加一个选项
