### ISSUE TITLE
Can the program search for subfolders?

### ISSUE THREAD

**Issue by bropines** [SchneeHertz/exhentai-manga-manager#172]
**Question**
The question is as follows. My folder structure is as follows.
```
Main-folder
└─── Artist name
    └─── Title name
        └─── title folder/archives
```
Will the program be able to take them into account when scanning or do I need to have everything in one folder?

**Comment by SchneeHertz** [comment]
The program will consider the following two types as manga:
1. Compressed files
2. Folders that directly contain image files, excluding images in subfolders
This is unrelated to the depth of the folder where the manga is located.
