### ISSUE TITLE
请求增加1、针对画廊地址屏蔽的功能/2、短画廊被引导到合集问题/3、筛选“页数没对上的画廊”的功能。

### ISSUE THREAD

**Issue by ax113** [SchneeHertz/exhentai-manga-manager#173]
1、下边这个链接只有一张图，但是这张图碰到 空気系☆漢化 这个组汉化的本子，就导致其他画廊扫描直接对到这个地址，这个是因为这个汉化组的招募图片通常被系统自动识别到封面了导致（大概
而且其他有些汉化组的招募图也会被识别成封面，但因为没多少人干下面这个链接这种事以及汉化组偶尔更新招募图，所以目前还好。
https://exhentai.org/g/1111177/4bbec052bd/
历史画廊也会出现这样的情况
https://exhentai.org/g/1686403/2dd0f527e4/
还有这个也是，会把这个作者的一些作品误导到这个链接
https://exhentai.org/g/3043243/908c2e5a55/
哪怕画廊都被隐藏了或者删除也没用

2、另外一个问题是许多很短的画廊被作者上传过p站，导致扫描的时候会把这些很短的画廊引导到image set的[pixiv]开头的p站合集里
![a](https://github.com/user-attachments/assets/ef3e2197-28df-4590-981b-b726b599b626)
![b](https://github.com/user-attachments/assets/2b82f5a6-22a6-4b28-ad2a-1bbcb06691f8)
因为纯小白完全看不懂代码，所以解法纯属乱想，一种可能的解法是针对这类画廊出现本地页数与反馈回来页数差距过大（几百页）且/或返回的画廊类型是image set或标题带pixiv/fanbox/parton/twitter的时候先降低优先级尝试其他反馈结果，没有匹配的再选这个。

3、请求加一个筛选页数没对上的画廊功能，方便后期手动修正画廊而不是万里挑一的找有问题的画廊

感谢作者！

**Comment by SchneeHertz** [comment]
1. 压缩包里汉化组的图放第一页这个无解，建议在软件内打开缩略图界面手动删除
2. 搜索和获取元数据不在同一步，不过我后续会考虑优化搜索结果
3. 搜pageDiff

**Comment by ax113** [comment]
好的，感谢！
