### ISSUE TITLE
最新版1.6.2不能读取使用1.5.15的元数据，会闪退

### ISSUE THREAD

**Issue by ltr123456789** [SchneeHertz/exhentai-manga-manager#175]
**Before giving feedback on a bug, please make sure that what you are giving feedback on is not explained in the wiki**
**在提供错误反馈之前，请确保您所反馈的内容在wiki中没有解释。**

**Describe the bug**
**描述错误**
对错误的清晰简明描述。

**Log**
**错误日志**
error log in log.txt in %AppData%\exhentai-manga-manager or in root of program file folder,
or console log of devtool
在%AppData%\exhentai-manga-manager文件夹中或程序文件夹的根目录中的log.txt，以及Devtool(在软件界面按F12打开)，显示的出错信息

**Screenshots**
**截图**
如果适用的话，请添加截图以帮助解释您的问题。

**Additional context**
**附加信息**
在这里添加有关问题的任何其他信息。

**Comment by SchneeHertz** [comment]
请提供更多的信息，如错误日志

**Comment by ltr123456789** [comment]
bookHashMetadata.json从1.6开始就不能导入这个文件，现在都是导入这个metadata.sqlite但是识别非常慢我以为是没有成功，还有1.6开始在软件内不能直接更换封面，更换后就直接黑屏了
![比特截图2024-09-20-20-33-10](https://github.com/user-attachments/assets/214d8f8f-3d7e-4dcb-a830-c16dcf7928a7)

**Comment by ltr123456789** [comment]
Get ex page failed because TypeError: Only absolute URLs are supported更换图片后会显示这个

**Comment by SchneeHertz** [comment]
现在更换了备份元数据的方式，还原应该是不需要等待的，因为是直接替换数据库文件

封面更换的bug在 #171 有记录，下个版本修
