### ISSUE TITLE
关于局域网浏览的相关问题

### ISSUE THREAD

**Issue by mzspeedwolf** [SchneeHertz/exhentai-manga-manager#177]
在Mihon中使用LANraragi设定完成后，LANraragi插件内只显示100本，通过搜索能检索到其他未显示的本，但即便重新打开Mihon也只显示100本。（重装插件也都是相同的100本）

请教一下这是我哪里没设定对还是LANraragi的问题又或者是软件功能问题

**Comment by SchneeHertz** [comment]
是这样的
在插件的界面有下一页的功能，你找一找

**Comment by mzspeedwolf** [comment]
感谢解惑！
（如此翻页甚是麻烦）
