### ISSUE TITLE
关于1.6.3新增.ehviewer获取url的功能使用方法

### ISSUE THREAD

**Issue by acientmoon2015** [SchneeHertz/exhentai-manga-manager#184]
不太清楚如何使用这个新功能，因为我都是使用ehviewer下载的本子，以《1785803-[Mr.takealook] Supergirl's Secret Service [Chinese] [不咕鸟汉化组]》这本为例，从手机导出到电脑是这样的文件夹形式：

然后使用bandizip压缩成同名zip，可以扫描到软件库中，选择元数据来源后获取失败显示tag-failed：

包括手动获取元数据也是显示无结果，但其他方式如exhentai(sha1)能正常获取tag

![Snipaste_2024-10-28_20-21-22](https://github.com/user-attachments/assets/f5b5e0d9-2535-47d2-89aa-5876ee57a0ab)

1.6.3介绍中写“增加从文件夹类型的漫画的.ehviewer文件获取exhentai url的功能 ”，我把原始文件夹形式丢进根目录，好像扫描不到，只能转成zip压缩包，但压缩包内有.ehviewer文件却无法正确识别。所以想询问下新功能的使用方式，不甚感激

**Comment by SchneeHertz** [comment]
只支持文件夹形式的漫画，就是第一张图的形式，整个文件夹放到库的文件夹或者子文件夹内
如果扫描不到可能是其他的问题

**Comment by acientmoon2015** [comment]
好的，谢谢！不过一般软件像lanraragi都只支持压缩包形式，重新打包成zip适用范围更多些。实在不行原来的tag获取方式也基本够准确了

**Comment by acientmoon2015** [comment]
感谢作者，已经没问题了。之前加了排除文件的正则表达式仅筛选zip，现在删了就能扫描到文件夹漫画了
