### ISSUE TITLE
添加功能请求及使用反馈1.63

### ISSUE THREAD

**Issue by lyuyuu** [SchneeHertz/exhentai-manga-manager#186]
大佬您好，从1.5.11更新到1.6.3，发现多了不少实用的功能，甚是欢喜。
不过在使用之余，有2个新增的功能实际个人使用效果欠佳，具体如下：

1. **1.5.17新增的增加页数差异大于5时高亮页数**
    个人因会对一些本子进行页数调整及删去部分广告页数，此功能红色高亮显示尤为吸引人视线
     大佬是否考虑添加此功能的开关，或者增加个人自定义颜色选择，或者支持用户对元数据页数的修改。

2. **1.6.1新增的阅读次数**
    理由同1，红色的填充色过于吸引人视线了，且此ui位置让人联系到游戏的红点，不自觉吸引注意力
    希望增加此功能开关及颜色定义，如果可以支持位置定义就更好了（如右下深色填充显示，不会像左上红色显示那样让人感觉是游戏的小红点）

**Comment by SchneeHertz** [comment]
1. 可以通过自定义css修改
2. 这个之前有人提过，我下个版本会调整颜色

**Comment by dx90c** [comment]
自定义css請問要如何做呢

**Comment by SchneeHertz** [comment]
> 自定义css請問要如何做呢

.book-card-pagecount { color: black; background-color: transparent; border-color: lightgrey; }

颜色你自己选
