### ISSUE TITLE
还原元数据问题

### ISSUE THREAD

**Issue by ltr123456789** [SchneeHertz/exhentai-manga-manager#187]
1.62元数据导入到1.63后合集不见了，是我文件导入错误吗

**Comment by SchneeHertz** [comment]
查看你导入的collectionList.json文件内容是否完整

**Comment by ltr123456789** [comment]
Uploading 无标题视频——使用Clipchamp制作.mp4…

是使用还原元数据这个选项吗，使用后导入collectionList.json后还会显示一次弹窗，在次点击也没有导入
![屏幕截图 2024-11-08 220214](https://github.com/user-attachments/assets/279a54bb-f079-4fa5-b0eb-5b36bc7cb7f7)

**Comment by SchneeHertz** [comment]
还原元数据要导入两个文件，看窗口标题的提示，第一个是collectionList.json，第二个是metadata.sqlite

**Comment by ltr123456789** [comment]
还是非常感谢你的解答，我也是没有注意弹窗上有提示选择那个文件夹，我也是不太仔细太疏忽
