### ISSUE TITLE
批量添加标签

### ISSUE THREAD

**Issue by ltr123456789** [SchneeHertz/exhentai-manga-manager#188]
在使用批量添加标签的时候如果标签中又（）括号这类标签出现错误提示导致无法添加

**Comment by SchneeHertz** [comment]
标签现在可用的字符有._- a-zA-Z0-9和汉字
其他字符不支持
下次更新我把()加上

**Comment by ltr123456789** [comment]
感谢，我还会用一些其他字符，有一部分是中文的括号（）逗号顿号等，也可以加上吗

**Comment by SchneeHertz** [comment]
不，其他的就不加了

**Comment by ltr123456789** [comment]
好吧

**Comment by ltr123456789** [comment]
能说一下会添加的就只有（）吗是中文的还是英文的，我修改一下我的标签，谢谢

**Comment by SchneeHertz** [comment]
> 能说一下会添加的就只有（）吗是中文的还是英文的，我修改一下我的标签，谢谢

() 半角的，英文一般使用的版本。

**Comment by ltr123456789** [comment]
好的

**Comment by ltr123456789** [comment]
你好这个批量添加标签可以把日文加上吗，毕竟大部分作者都是日文名

**Comment by SchneeHertz** [comment]
用罗马音，和e-hentai的tag保持一致
