### ISSUE TITLE
类似名字的文件，会被整合到一起

### ISSUE THREAD

**Issue by ltr123456789** [SchneeHertz/exhentai-manga-manager#189]
如果文件夹中有名字相同的文件会被整合到一起比如图集其1和图集其12，图集12的漫画会显示在图集其1中，如图，我选择的图集1，可是他把图集12的文件也整合进去了，我一个文件夹是300个文件
![屏幕截图 2024-11-11 220607](https://github.com/user-attachments/assets/62bdbd4a-f45d-4053-b746-8b13fcaad1f7)
![屏幕截图 2024-11-11 221148](https://github.com/user-attachments/assets/2578e23e-dd93-4c4b-83ac-35c09c990eca)

**Comment by SchneeHertz** [comment]
是bug，下个版本修
