### ISSUE TITLE
添加对漫画织机元数据的支持

### ISSUE THREAD

**Issue by zizzdog** [SchneeHertz/exhentai-manga-manager#190]
鉴于好多版权本在eh根本找不到，而且其他站点下载器的tag数据又是比较混乱，找到了一个叫漫画织机的项目，不同站点下载时生成的元数据比较统一较容易处理，可以考虑兼容
漫画织机https://github.com/MapoMagpie/eh-view-enhance

**Comment by SchneeHertz** [comment]
参考 #183
