### ISSUE TITLE
1.6.3版本获取元数据出错

### ISSUE THREAD

**Issue by njjzx** [SchneeHertz/exhentai-manga-manager#191]
在今天之前，使用通过网址获取元数据是正常的，但是今天获取出错。我用网页浏览是OK的
软件版本是最新的1.6.3

**Log**
**错误日志**
Get ex page failed because FetchError: request to https://exhentai.org/g/3126263/cff53284d1/ failed, reason: Client network socket disconnected before secure TLS connection was established
Get ex data failed because FetchError: request to https://api.e-hentai.org/api.php failed, reason: Client network socket disconnected before secure TLS connection was established
Saved [にのこや (にの子)] 少女回春11完結編＋AFTER [中国翻訳] [DL版].zip

通过hentag获取元数据也是正常的

**Comment by SchneeHertz** [comment]
这个错误是梯子不稳定导致的，换个节点应该就好了
