### ISSUE TITLE
扫描到一半就卡住了，没有任何报错

### ISSUE THREAD

**Issue by Rex1987** [SchneeHertz/exhentai-manga-manager#194]
**Before giving feedback on a bug, please make sure that what you are giving feedback on is not explained in the wiki**
**在提供错误反馈之前，请确保您所反馈的内容在wiki中没有解释。**

**Describe the bug**
**描述错误**

扫描到这边就卡住了，放了一天读条也没前进，前台和log都没报错

**Log**
**错误日志**

Empty Exist BookList and Saved New BookList
Unhandled Rejection at: Promise { <rejected> [Error: Failed to parse path] } reason: [Error: Failed to parse path]
Unhandled Rejection at: Promise { <rejected> [Error: Failed to parse path] } reason: [Error: Failed to parse path]
Start loading library
Load 3954 book from library

**Screenshots**
**截图**
![image](https://github.com/user-attachments/assets/19f19770-6296-4820-9ee3-3f3f8ba92304)

**Comment by Rex1987** [comment]
应该这么说，我把能解决的报错全解决了，然后清空了缓存目录重新扫的，但是还是扫到这边就停住了

**Comment by SchneeHertz** [comment]
请问库文件夹设置是什么，是否在特殊的位置

**Comment by Rex1987** [comment]
> 请问库文件夹设置是什么，是否在特殊的位置

![image](https://github.com/user-attachments/assets/4f16325c-1204-44c3-ba2a-b4c5f71cdf7f)
"library": "F:\\e-hentai",
  "metadataPath": "F:\\data",
就在普通的文件夹，没有设置任何权限

**Comment by SchneeHertz** [comment]
没有错误信息确实很奇怪，我暂时也不清楚是什么原因

**Comment by Rex1987** [comment]
> 没有错误信息确实很奇怪，我暂时也不清楚是什么原因

能不能打一个扫描进度的log，我看看是扫到哪个文件的时候卡住了

**Comment by SchneeHertz** [comment]
> > 没有错误信息确实很奇怪，我暂时也不清楚是什么原因
> 
> 能不能打一个扫描进度的log，我看看是扫到哪个文件的时候卡住了

这是一个临时的portable版本，会打印每一个扫描的文件到log.txt
https://wormhole.app/RDWMY#x9YvhlJJkCIhjaD3R45kMw

**Comment by Rex1987** [comment]
找到部分问题了，在扫描时碰到以“.zip”结尾的“文件夹”文件会出现问题
这种文件的来源是：
以前使用mac系统时，mac解压zip时会自动给zip文件创建一个“.zip”结尾的文件夹，且会把原本的zip文件和解压后的文件都放进该文件夹中
类似下图：
![image](https://github.com/user-attachments/assets/8b4a7a10-1f97-439a-b2e7-2fe945a2d802)
![image](https://github.com/user-attachments/assets/e02a3db5-2e8c-4e56-bafc-1f269c9c25f3)
如需要的话我可以提供一些文件样本供你分析

**Comment by SchneeHertz** [comment]
了解了，这个软件扫描时是用文件后缀判断应该使用哪个方法处理，而将.zip结尾的文件夹误认为是压缩包，导致解压程序卡住
之后我会处理此类错误，以使扫描过程能够继续进行
