### ISSUE TITLE
内置阅读器的左右翻页功能在最上层

### ISSUE THREAD

**Issue by Armageddon-15** [SchneeHertz/exhentai-manga-manager#195]
单页和双页都在最上层
这样在用鼠标修改左上的设置或者右上退出都会翻页，开启自动下一本时如果在尾页会在鼠标点击关闭按钮后直接到下一本

另外有自动下一本会不会有自动上一本的功能

**Comment by SchneeHertz** [comment]
是bug，已经有人反馈，下个版本修
上一本下一本有快捷键PageUp PageDown
