### ISSUE TITLE
搜索功能无效

### ISSUE THREAD

**Issue by Rex1987** [SchneeHertz/exhentai-manga-manager#198]
**Before giving feedback on a bug, please make sure that what you are giving feedback on is not explained in the wiki**
**在提供错误反馈之前，请确保您所反馈的内容在wiki中没有解释。**

**Describe the bug**
**描述错误**

搜索输入框填入任何内容点击搜索都没有效果

**Log**
**错误日志**

mei'you没有任何log信息

**Screenshots**
**截图**
![image](https://github.com/user-attachments/assets/88af40d2-1798-4022-abdf-6e6675058b62)

**Additional context**
**附加信息**
在这里添加有关问题的任何其他信息。

**Comment by SchneeHertz** [comment]
排序方式选一下，再搜索应该就可以了

**Comment by Rex1987** [comment]
感谢，可以了
