### ISSUE TITLE
批量获取元数据失败

### ISSUE THREAD

**Issue by pikawindy** [SchneeHertz/exhentai-manga-manager#2]
我有ex的账号，设置里ex的三项数据也填了，但点击批量获取元数据或ex元数据，就会出现这图
![Snipaste_2022-05-30_18-14-11](https://user-images.githubusercontent.com/63467634/170971341-d114f1f2-5111-4970-b688-2c8999beba3b.png)
处理完后还是显示non-tag，只能手动输入e站网址获取数据。
开了梯子，网站浏览器能正常打开，软件里设置了代理服务器也是不行，请问如何解决啊

**Comment by SchneeHertz** [comment]
如果输入e站网址后能获取到元数据的话, 应该是获取e站网址这个步骤出了问题, 你再检查ex cookie的三个值是不是填的有问题

**Comment by SchneeHertz** [comment]
> 我有ex的账号，设置里ex的三项数据也填了，但点击批量获取元数据或ex元数据，就会出现这图 ![Snipaste_2022-05-30_18-14-11](https://user-images.githubusercontent.com/63467634/170971341-d114f1f2-5111-4970-b688-2c8999beba3b.png) 处理完后还是显示non-tag，只能手动输入e站网址获取数据。 开了梯子，网站浏览器能正常打开，软件里设置了代理服务器也是不行，请问如何解决啊

出错后在软件界面按Ctrl+Shift+i, 看看console有没有打印错误信息

**Comment by SchneeHertz** [comment]
> > > 我有ex的账号，设置里ex的三项数据也填了，但点击批量获取元数据或ex元数据，就会出现这图 ![Snipaste_2022-05-30_18-14-11](https://user-images.githubusercontent.com/63467634/170971341-d114f1f2-5111-4970-b688-2c8999beba3b.png) 处理完后还是显示non-tag，只能手动输入e站网址获取数据。 开了梯子，网站浏览器能正常打开，软件里设置了代理服务器也是不行，请问如何解决啊
> > 
> > 
> > 出错后在软件界面按Ctrl+Shift+i, 看看console有没有打印错误信息
> 
> 我也出现同样问题 打印错误信息为 index.html:1 Uncaught (in promise) Error: Error invoking remote method 'get-ex-url': Error: Client network socket disconnected before secure TLS connection was established 关闭代理后错误信息为 Uncaught (in promise) Error: Error invoking remote method 'get-ex-url': Error: connect ETIMEDOUT 128.121.243.77:443

这是代理服务器连接不了或者设置错误

**Comment by ppj12345** [comment]
> 

是不是由于代理连接exhentai比较慢，获取接口数据超时导致的？

**Comment by pikawindy** [comment]
> > > 我有ex的账号，设置里ex的三项数据也填了，但点击批量获取元数据或ex元数据，就会出现这图 ![Snipaste_2022-05-30_18-14-11](https://user-images.githubusercontent.com/63467634/170971341-d114f1f2-5111-4970-b688-2c8999beba3b.png) 处理完后还是显示non-tag，只能手动输入e站网址获取数据。 开了梯子，网站浏览器能正常打开，软件里设置了代理服务器也是不行，请问如何解决啊
> > 
> > 
> > 出错后在软件界面按Ctrl+Shift+i, 看看console有没有打印错误信息
> 
> 我也出现同样问题 打印错误信息为 index.html:1 Uncaught (in promise) Error: Error invoking remote method 'get-ex-url': Error: Client network socket disconnected before secure TLS connection was established 关闭代理后错误信息为 Uncaught (in promise) Error: Error invoking remote method 'get-ex-url': Error: connect ETIMEDOUT 128.121.243.77:443

我同样的显示。。
我确定ex cookie的设置是没错的，我也能打开ex网站，可能是代理服务器出错？
我是开v2rayn，然后复制http://45.12.110.8到代理服务器里的，是不是这里有问题？
![Snipaste_2022-05-31_21-37-42](https://user-images.githubusercontent.com/63467634/171187090-f33855bc-7b6b-4588-9e0f-37b79ae2f12e.png)
其实我不怎么理解代理服务器，一般不是像别的网站一样，只要开了梯子，就能连接外网了吗？

**Comment by SchneeHertz** [comment]
@pikawindy 这个是远程的服务器的地址，设置里要填的是本地的监听地址，你用的是v2rayN吧，设置v2的系统代理，然后在v2的窗口左下会有http的监听地址，类似于http 127.0.0.1:XXXX
在设置里填入http://127.0.0.1:XXXX就行
