### ISSUE TITLE
路径无法识别

### ISSUE THREAD

**Issue by Smile8848** [SchneeHertz/exhentai-manga-manager#20]
[![vVLYFg.png](https://s1.ax1x.com/2022/08/03/vVLYFg.png)](https://imgtu.com/i/vVLYFg)
点阅读按钮只能跳到此电脑

**Comment by SchneeHertz** [comment]
要在设置里设置默认打开程序，否则默认是用资源管理器打开
也可以点击封面使用内置的阅读器
