### ISSUE TITLE
希望能增加panda.chaika.moe这个网站作为元数据来源

### ISSUE THREAD

**Issue by SoranoIkaros** [SchneeHertz/exhentai-manga-manager#200]
panda.chaika.moe这个网站主要收录的是被EH删除，不过站内没有汉化本，只适合作为日文原版的tag获取

**Comment by bennyz327** [comment]
原本有加 (#78)
後來作者刪掉 (#160)

蠻可惜的，如果需要從 chaika 拿資料，可以考慮用 lanraragi

給你參考

**Comment by SchneeHertz** [comment]
因为使用场景过少，这个功能已经移除了
