### ISSUE TITLE
manager内无法访问ex，表站正常，而且无法从用网址获取元数据。

### ISSUE THREAD

**Issue by KuonType** [SchneeHertz/exhentai-manga-manager#201]
具体问题描述一下。
浏览器正常访问表里站，无熊猫。配置的三个账号信息内容无误，使用其他E站漫画阅读如jhentai验证过填入的三条信息无误，可以正常登录里站。
![001](https://github.com/user-attachments/assets/bd82e13b-a919-4d18-8c0f-27930c90f0c1)

问题1 可以在手动获取元数据里通过e-hentai(SHA1)查询到漫画，但是exhentai(SHA1)就一直读取中。
问题2 在手动获取元数据后，网页被填入后，用网址获取元数据功能按钮按了也无效。（但是用油猴插件从剪贴板获取元数据导入是OK的）
![002](https://github.com/user-attachments/assets/a541dc95-c118-4190-913d-1503981ccb45)
这2个问题也没有log.txt的日志输出。。

问题3 批量获取元数据也是无效的，把数据源填取自表站也是填入不了的。（目前是通过导入api_dump.sqlite导入的一大把数据）

期间通过exe安装包或者zip的解压版都是一样的问题，exe卸载后我把Roaming里面的数据也清空了才装的zip版本的，然后重新扫描入库也是一样的问题。

操作系统是Windows 11 企业版 X64系统
还请大大帮忙分析一下可能的远因。。。

**Comment by SchneeHertz** [comment]
代理服务器填http://127.0.0.1:7890/试试

**Comment by KuonType** [comment]
> 代理服务器填 http://127.0.0.1:7897/ 试试

可以了，需要填http://127.0.0.1:7897。
是默认给https了吗还是什么原因。。习惯了不输入http协议了。。。
谢谢大佬解决问题。。
