### ISSUE TITLE
添加功能请求：删除本地文件

### ISSUE THREAD

**Issue by recccc68a** [SchneeHertz/exhentai-manga-manager#203]
库相对来说比较大，能不能添加一个删除本地文件夹的关联菜单这样也好方便筛选整理。

右键菜单里删除文件的说明是从软件中移除并删除本地文件
但是测试了一下具体执行的只有删除了软件的显示，本地漫画的文件夹还在

**Comment by SchneeHertz** [comment]
我试了下能删文件夹形式的漫画，有没有报错信息？

**Comment by recccc68a** [comment]
我这边漫画的格式是图片，存储在nas，电脑访问的是网络位置，删除软件里的文件夹只能让软件里记录消失
没办法删除漫画里独立的页面，菜单选删除没反应，在文件夹中删除页面的话就直接删除成功不会报错
报错的话只有手动扫描之后才会有error

**Comment by SchneeHertz** [comment]
如果硬盘上的单张图片或整个文件夹都不能删除，应该是文件权限方面的问题，我这边没有测试条件，没办法得到进一步的信息

**Comment by recccc68a** [comment]
用管理员身份运行的话连原来的库都调用不了，常规的硬盘库会有这样的问题吗

**Comment by SchneeHertz** [comment]
应该是NAS上的文件权限，如果你是将NAS的存储位置挂载到Windows的盘符上，试一下能不能在资源管理器中将文件删除到回收站

**Comment by ax113** [comment]
作者你好，我也和楼主碰到了一样的问题，我使用的是win nas，nas那边使用管理员完全读写权限smb共享的磁盘，此时在本地资源管理器中可以正常删除漫画文件。当本地同样使用的管理员权限打开软件，出现了同楼主一样的问题（无法删除漫画，不管是文件夹还是单独里边的图片）。

**Comment by ax113** [comment]
通常来说如果要从本地删除一个nas上的文件（如通过smb共享的文件夹），在删除的时候会且只会弹出是否确认永久删除文件，此时如果点击确认，那么此文件会永久删除，而不是会进入nas的回收站。（远程就是这样，删除没法后悔）
此外，有一个操作是可以在a电脑上找一个文件夹设置共享，然后a电脑再通过映射网络驱动器的方式挂上这个本地的共享文件夹，这样虽然看着文件夹还是在本地，但是在系统看来这就是个远程smb过来的网络驱动器，和在nas上没区别。我也通过这个方式用软件确认了他确实删不了远程的漫画文件，哪怕这个文件就在本地，用的也是管理员权限。

**Comment by SchneeHertz** [comment]
现在用的方法不能删除smb协议的文件，因为现在的删除操作实际上是移动到回收站
我增加了一个fallback，将不能移动到回收站的文件直接删除

漫画内的图片不能删除是另外一个bug，也已经定位到问题原因

以上修复会在下个版本发布
