### ISSUE TITLE
导出元数据时缺失category属性

### ISSUE THREAD

**Issue by wujiang037** [SchneeHertz/exhentai-manga-manager#3]
你好，请问可以在导出元数据时包含漫画的category属性吗？现在版本不包含这个属性，重新导入元数据后漫画类别为空。谢谢！

![image](https://user-images.githubusercontent.com/78885852/171899530-3b628b5f-8811-47dc-a402-9b661d19fb41.png)

**Comment by SchneeHertz** [comment]
> 你好，请问可以在导出元数据时包含漫画的category属性吗？现在版本不包含这个属性，重新导入元数据后漫画类别为空。谢谢！
> 
> ![image](https://user-images.githubusercontent.com/78885852/171899530-3b628b5f-8811-47dc-a402-9b661d19fb41.png)

 感谢反馈，下个版本会修复这个问题

**Comment by SchneeHertz** [comment]
@wujiang037 版本1.3.5已发布，已经修复了这个问题

**Comment by wujiang037** [comment]
@SchneeHertz 多谢!
