### ISSUE TITLE
How to translate tags into english?

### ISSUE THREAD

**Issue by VanTuz5** [SchneeHertz/exhentai-manga-manager#30]
How to translate tags in the program into English? The program loads only in Chinese, but I don't know it.
And how to add file to gallery? Rescan all collection?

**Comment by SchneeHertz** [comment]
You can turn off the **Tag Translate** switch in **Setting** - **Advanced** to disable tag translating.
Use **Setting** - **General** - **Manual Scan** for add manga to library when you added file to library folder.

**Comment by VanTuz5** [comment]
Thanks a lot
