### ISSUE TITLE
In some folders, the program does not see all the files.

### ISSUE THREAD

**Issue by VanTuz5** [SchneeHertz/exhentai-manga-manager#31]
In some folders, the program does not see all the files. The files have the .cbz extension, like all the others, but the program still does not see them.

**Comment by SchneeHertz** [comment]
Can you provide the content of log.txt file in %AppData%\exhentai-manga-manager,  or in root of program file folder for portable version after scan?

**Comment by VanTuz5** [comment]
[log.txt](https://github.com/SchneeHertz/exhentai-manga-manager/files/9653360/log.txt)

**Comment by SchneeHertz** [comment]
@VanTuz5 

> load E:\pictures\h\манга\peritian\[Peritian] Cats Love Water 5 - Котики любят водичку 5 [Russian] [Kozzy].cbz, 5288 of 6757
close code is 2

This error is usually caused by an encrypted zip file, which is not supported by this software

**Comment by VanTuz5** [comment]
It was downloaded from EX. How can I remove the encryption?

**Comment by SchneeHertz** [comment]
I'm sorry, but I haven't considered supporting encrypted zip files as a feature recently

**Comment by VanTuz5** [comment]
I don't understand anything. I rearchived the images to remove the encryption, but the program still does not see the files. What am I doing wrong?
