### ISSUE TITLE
The program still does not see all the files.

### ISSUE THREAD

**Issue by VanTuz5** [SchneeHertz/exhentai-manga-manager#33]
I'm completely confused. I archived files with the same archiver in the same format (7z), but the program still does not see some of the files, and I don’t understand at all what the problem is. What am I doing wrong? At the beginning of the log, the program writes that it cannot find the file, although it exists, but for some reason the program does not want to see it.
[log.txt](https://github.com/SchneeHertz/exhentai-manga-manager/files/9669192/log.txt)

**Comment by VanTuz5** [comment]
Well, zipping with peaseip seems to have helped. But the thumbnails are not always displayed, you have to manually scan again. And the program has obvious problems with the 7z archives, for some reason it does not see some of them.

**Comment by SchneeHertz** [comment]
It is a known issue that the 7zip decompressor used by this software does not handle some Unicode characters. I use another decompression program to handle Zip archives, but there is no good solution for other formats right now.

I suggest you use use use Zip format when packing.

**Comment by VanTuz5** [comment]
What about thumbnails?

**Comment by SchneeHertz** [comment]
@VanTuz5 This means the image file is corrupt, refer to [sharp/1859](https://github.com/lovell/sharp/issues/1859).
For some reasons and I believe that manga should not include gif, this software does not support gif.

**Comment by VanTuz5** [comment]
I rearchived the files that the program did not see and it saw them. But not all files have thumbnails displayed, so the ability to manually update the thumbnail is still needed.

**Comment by SchneeHertz** [comment]
You can right click on a thumbnail to assign it as a cover, or if you are looking for a bulk approach, use the PatchLocalMeta button in Settings - Advanced

When performing patching local metadata, if an interruption occurs, some manga will appear without a cover
