### ISSUE TITLE
The program does not find metadata

### ISSUE THREAD

**Issue by VanTuz5** [SchneeHertz/exhentai-manga-manager#37]
When I choose to get ex metadata, the program finds anything but what I need, even if a manual search shows that this comic is on the site with the same name as the file. Getting metadata by file name also does not always work.

**Comment by SchneeHertz** [comment]
Although uncommon, I have encountered this problem a few times and unfortunately I have not found the cause. This only seems to happen with recently uploaded galleries

**Comment by SchneeHertz** [comment]
I found out that some Image Set on exhentai contain images from other manga, so the search tends to hit the wrong galleries, I plan to exclude the Image Set search results in the next version
