### ISSUE TITLE
调用其他看图软件的问题

### ISSUE THREAD

**Issue by zbt000** [SchneeHertz/exhentai-manga-manager#39]
之前资源太混乱所以下了一直没使用，今天资源盘重整理后开始用了
想提个建议
调用其他看图软件的时候能否改为用第一张图片打开，现在应该是文件夹打开，有的软件用文件夹打开为空，但我想能支持文件夹打开的看图软件一般也支持用第一张图片打开然后顺序浏览
比如我用的这款很好用的看图软件，是我目前找到的唯一一个在瀑布流的同时滚动翻页还不会跳页的，其他大多数软件都会跳页，比如第一页滚动到第二页的时候，会把滚动了一半的第一页瞬间滚完，第二页的上端直接出现在页面上端
https://github.com/qdaxb/mangaviewer

**Comment by SchneeHertz** [comment]
[qdaxb/mangaviewer](https://github.com/qdaxb/mangaviewer) 我用过，目前是不支持命令行的，所以和本软件不兼容。
如果你偏好卷轴式浏览，可以试一下内置的浏览界面
