### ISSUE TITLE
【UI改进建议】希望可以添加左侧文件夹树宽度调节以及主界面封面大小/列数量选择

### ISSUE THREAD

**Issue by katyurua** [SchneeHertz/exhentai-manga-manager#41]
## 1. 希望可以添加左侧文件夹树宽度调节
 左侧文件夹树的宽度无法单独调节，只能通过调节整个窗口大小来勉强调节一点，有时文件夹名较长显示不全。
***
## 2. 希望添加主界面封面大小或列数量的调节
 大概就像缩略图那样能手动选择列数，而不是通过调节窗口大小来调整一点。
***
感谢作者，目前个人的刮削及管理使用体验已经超过[LANraragi](https://github.com/Difegue/LANraragi)了，
用户界面友好，网络设置也很方便，刮削也很快捷。

**Comment by SchneeHertz** [comment]
1可以
2封面的UI基本是固定的，如果你确实需要调整封面的UI大小，可以通过Ctrl++和Ctrl+-的快捷键调节缩放比例

**Comment by katyurua** [comment]
> 1可以 2封面的UI基本是固定的，如果你确实需要调整封面的UI大小，可以通过Ctrl++和Ctrl+-的快捷键调节缩放比例

主要是为了更改列数，封面大小倒是其次。
不过Ctrl++缩放试了下无效。窗口化和全屏下都试了。
不过我猜测就算有效也会导致字体变小吧，像chrome那样？，不清楚Electron。

**Comment by SchneeHertz** [comment]
文件夹树宽度设置功能已增加到最新版
