### ISSUE TITLE
[功能请求]

### ISSUE THREAD

**Issue by Smile8848** [SchneeHertz/exhentai-manga-manager#45]
![QGKKPTUA3$1B2WG4GM9XY4I](https://user-images.githubusercontent.com/31927778/208221184-bdca51b0-0eff-4bb7-afd7-5768f7828344.png)
可以在这里增加页数的显示吗？有些时候不是很想看太长篇幅的

**Comment by SchneeHertz** [comment]
没位置放了，而且我觉得没什么必要
