### ISSUE TITLE
能否支持一下自定义文件管理器

### ISSUE THREAD

**Issue by Smile8848** [SchneeHertz/exhentai-manga-manager#47]
我记得之前版本是支持自定义文件管理器的？

**Comment by SchneeHertz** [comment]
你可能指的是默认外置阅读器的设置，默认是Windows的文件管理器。
在设置里修改

**Comment by Smile8848** [comment]
> 你可能指的是外置阅读器的设置，默认是Windows的文件管理器。 在设置里修改

  我尝试更改使用了一下貌似不是我预期的，其实是想更改[打开漫画目录]这个功能发送到的文件管理器，因为它默认是系统的文件管理器。。

**Comment by SchneeHertz** [comment]
打开漫画文件所在目录这个功能过去和现在都是不支持自定义打开所用的文件管理器的，也没有计划增加这个设置
