### ISSUE TITLE
特定壓縮包無法被導入

### ISSUE THREAD

**Issue by bennyz327** [SchneeHertz/exhentai-manga-manager#49]
版本1.4.5

檢查時發現硬碟的文件數量和管理器掃瞄出的數量不一樣，最後找到一個zip檔案是沒有被導入的
文件名:[脸肿汉化组] (C88) [AliceCreation (るく)] かしこまサービスタイム (プリパラ)

Log截圖:
![螢幕擷取畫面 2023-01-17 144047](https://user-images.githubusercontent.com/96097874/212829665-c67572f6-ca42-4890-9dae-ad0d63fd2988.png)

備註1:同路徑底下其他zip包都可以正常導入，裡面也都同樣是單純的jpg檔案
備註2:該檔案裡面的圖片解壓縮後是可以正常開啟的，嘗試過解壓後重新使用Bandzip無損打包，並執行手動掃描，仍然無法被管理器導入

**Comment by SchneeHertz** [comment]
应该是压缩包内的图片文件存在错误导致软件的图片处理模块不能解析
你可以尝试转换压缩包内图片的格式后重新打包，但如果e-hentai的画廊本来就是使用了有错误数据的图片，将不能自动获取到画廊的元数据，需要手动获取
