### ISSUE TITLE
向压缩包内添加元数据

### ISSUE THREAD

**Issue by answork02** [SchneeHertz/exhentai-manga-manager#50]
常用漫画（同人志）管理软件[LANraragi](https://github.com/Difegue/LANraragi)、[HappyPandaX](https://github.com/happypandax/happypandax)均支持压缩包内的`info.json`文件（[HPX plugin](https://github.com/happypandax/plugins/tree/master/plugins/File%20Metadata/); [eze](https://dnsev-h.github.io/eze/)格式）。
[exhentai-manga-manager](https://github.com/SchneeHertz/exhentai-manga-manager)对元数据刮削支持很好，请问能否考虑此类联用方法。

**Comment by SchneeHertz** [comment]
原则上，exhentai-manga-manager不会对漫画文件本身进行修改。
我之前考虑过在同文件夹下存放一个同名的元数据文件，但没有找到确实的需要来使用这个文件。如果是为了存档元数据，exhentai-manga-manager已经内置了整个库的元数据导出的功能。如果是为了和其他类似用途的软件兼容，目前并没有一个关于元数据的统一规格，这一点也很难做到。
所以我目前没有做这个功能的计划。

**Comment by answork02** [comment]
感谢回复。
[LANraragi](https://github.com/Difegue/LANraragi)支持读取同名json文件（[eze](https://dnsev-h.github.io/eze/)格式），不过确实需求此功能的人估计应该很少。
关于元数据，[eze](https://dnsev-h.github.io/eze/)格式是一个目前很多软件支持读取的格式，但的确没有任何形式的（包括事实上的）标准。
