### ISSUE TITLE
库文件夹下的同名文件夹内容在左侧文件夹树中错误显示

### ISSUE THREAD

**Issue by tyfkyufru** [SchneeHertz/exhentai-manga-manager#51]
不知道算不算bug，库中的同名文件夹均会显示其中一个文件夹的内容，如图。
![屏幕截图 2023-01-31 001845](https://user-images.githubusercontent.com/111337078/215534826-8ce4922d-ab3e-4203-9338-724715ce15a7.png)
更改两个文件夹中一个文件夹的名称后则可以正常显示：
![屏幕截图 2023-01-31 002039](https://user-images.githubusercontent.com/111337078/215535308-0a131a0a-16b2-4619-ae3b-69937150de15.png)

**Comment by SchneeHertz** [comment]
是bug，我已经定位到出错的地方，下个版本会修复 @tyfkyufru

**Comment by SchneeHertz** [comment]
已在v1.4.6修复
