### ISSUE TITLE
一旦"tag-failed"，就不能重新获得信息了

### ISSUE THREAD

**Issue by nxoet** [SchneeHertz/exhentai-manga-manager#53]
比如一次获得100本漫画的信息，到第50本时网络断了，那么，后面50本就"tag-failed"了，弄好网络，再次点击获得数据，这时后面这50本不变了，被判死刑了，只能点进详情页，把"tag-failed"标签重新选择为"non-tag"，这时点击获得数据才有用了，数量多的话，要一本一本去改成"non-tag"，很麻烦。

**Comment by SchneeHertz** [comment]
tag-failed状态是设计给eh上没有对应画廊的结果的情况，以避免批量获取元数据时反复搜索这些不能获得元数据的漫画
不过出于例外情况，我会在设置处加一个批量获取时搜索哪些状态的漫画

**Comment by SchneeHertz** [comment]
已增加此设置选项
