### ISSUE TITLE
批量匹配元数据到一定数量会引起崩溃

### ISSUE THREAD

**Issue by sohiidayo** [SchneeHertz/exhentai-manga-manager#54]
在初次使用批量获取元数据时，到达个数550左右崩溃，后期程序占用内存飙升，到达5500mb左右崩溃。
因为崩溃，匹配到的元数据全部化作无意义的等待了（哭）希望能匹配一个就写一个到数据库里。
重现过很多次了。能稳定触发这个bug。
即使不是从开头开始匹配的（例如在没有连接vpn时显示匹配750个时，连接vpn进行匹配，也是大概匹配500个左右崩溃）
希望能增加：范围选择+元数据匹配，通过标签推荐下一本，能主动停止或停止批量元数据匹配
使用了vpn，能手动匹配ehentai，无法连接ex。

数据分析这个功能我很喜欢，可以看出多年积蓄的本本成分，和自己的累计的审美观念。希望能增加多点球球在里面。甚至可以做联系图，不同的标签像线一样连接不同的本本，就像通过神经细胞组成人脑一样，组成属于自己的绅士（xp）宇宙……

**Comment by SchneeHertz** [comment]
使用前你需要看一下wiki https://github.com/SchneeHertz/exhentai-manga-manager/wiki

获取大量元数据时一般会碰到EH的IP限制，不太推荐一次获取200本以上数量的元数据。
一般推荐的做法是使用导入Sqlite数据库的功能获取到一部分本子的元数据后，剩余的部分再用批量获取。（这里有个写入bug，导致大量获取时内存溢出，我之后会修复）
EX的访问需要填写Cookie值，请参考wiki的设置

**Comment by SchneeHertz** [comment]
写入bug已修复
