### ISSUE TITLE
希望能添加来自EhViewer的压缩包时，获取.ehviewer内的数据。

### ISSUE THREAD

**Issue by sohiidayo** [SchneeHertz/exhentai-manga-manager#55]
来自EhViewer的压缩包内有.ehviewer文件
以文本打开的话在第3和第4行包含了gid和token两个值。

有了gid和token可以拼出本本的链接:https://e-hentai.org/g/gid/token或者https://exhentai.org/g/gid/token

希望：
导入压缩包时能将这个文件利用起来。
用sqlite匹配数据时能将这两个值利用起来
举例：色の教科書
.ehviewer开头部分
![image](https://user-images.githubusercontent.com/96026229/216572878-abeaa5e9-22c4-48fc-9abe-6065d2ee047f.png)
EhViewer界面
![image](https://user-images.githubusercontent.com/96026229/216573324-1bfa4fa8-8e8d-42d9-9539-c93c4026768b.png)
![image](https://user-images.githubusercontent.com/96026229/216573517-b08a7447-d18a-4400-980c-4f22c1539dd8.png)
sqlite查询gid：
![image](https://user-images.githubusercontent.com/96026229/216574660-a943cc1d-158e-4d13-893e-ac2af01cb186.png)
提供测试用：（分卷压缩 ）
https://github.com/sohiidayo/test

**Comment by SchneeHertz** [comment]
近期还没有支持其他第三方软件的计划，之后再说

**Comment by PiDanShouRouZhouXD** [comment]
提供一个临时的解决方案：
只需要在index.js的743行后加入如下的代码，就能最简单的实现通过token匹配数据库的功能。（前提是你的文件不是压缩包）
ehviewer = book.filepath + "\\.ehviewer"
let fileContent = fs.readFileSync(ehviewer, 'utf-8')
let lines = fileContent.split('\n')
let gallery_token = lines[3]
console.log('token:', gallery_token)
let metadata = await db.get(`SELECT * FROM gallery WHERE token LIKE '${gallery_token}'`);
此外，这个段代码没有任何的异常处理，请保证你的所有文件夹内都含有正确的“.ehviewer”文件（

**Comment by Qinolion** [comment]
如果要自己打包成exe安装包应该怎么弄

**Comment by SchneeHertz** [comment]
> 如果要自己打包成exe安装包应该怎么弄

git clone之后
`npm i`
`npm run dist`

**Comment by Qinolion** [comment]
好的，谢谢

SchneeHertz ***@***.***> 于 2024年1月29日周一 20:59写道：

**Comment by PiDanShouRouZhouXD** [comment]
https://github.com/SchneeHertz/exhentai-manga-manager/pull/174
我写好了
<img src="https://github.com/user-attachments/assets/58ed415e-21cd-42a3-a929-bcdb1a95c5f0"  width="75" >
