### ISSUE TITLE
从sqlite中获取元数据失败。

### ISSUE THREAD

**Issue by sohiidayo** [SchneeHertz/exhentai-manga-manager#56]
从sqlite导入时发生了导入失败的情况。
例如：
在sqlite中查询title或title：
![image](https://user-images.githubusercontent.com/96026229/216592490-c66ad47a-2b92-406e-b615-5b200f3393eb.png)
在程序中的界面(已经导入过了)：
![image](https://user-images.githubusercontent.com/96026229/216593692-697b116b-afa9-4d42-bd85-455f61755742.png)
也有成功的例子↓
在sqlite中查询title或title：
![image](https://user-images.githubusercontent.com/96026229/216593858-aab03ecb-dee3-40c8-b5fc-3ed82c300614.png)
在程序中的界面(已经导入过了)：
![image](https://user-images.githubusercontent.com/96026229/216595531-4e25333e-3663-4a15-8d1f-882efdedf52b.png)

大部分都是识别不到的（在sqlite里查询却查询却可以）
部分log.txt
![image](https://user-images.githubusercontent.com/96026229/216595946-a44bb8fa-0220-4147-9d3d-3129b8aaee4b.png)

**Comment by SchneeHertz** [comment]
从sqlite导入元数据是通过图片hash来匹配的，匹配不成功通常是因为你本地的漫画文件与EH网站上的不一致所导致的
一般来说漫画是使用EH网站上的存档下载功能下载，或者通过EH画廊的种子下载，使用本软件会有比较好的效果，其他来源的漫画不能保证能正确匹配到元数据
