### ISSUE TITLE
是不是用进度条表示更好一些？

### ISSUE THREAD

**Issue by lhj5426** [SchneeHertz/exhentai-manga-manager#58]
![image](https://user-images.githubusercontent.com/30548000/217296152-e7bf3aba-0273-4be6-a341-c15565a3c468.png)

加载的时候 是不 是用进度条来表示比这样来回 跳 要好一些？

现在这样感觉不够直观

排序可以用创建时间吗？
![image](https://user-images.githubusercontent.com/30548000/217297449-d6b5e73a-3be8-436a-bfab-273b8e3ecfb9.png)

![image](https://user-images.githubusercontent.com/30548000/217297352-cc860cc8-e3a7-4601-97d5-d71bdcd2066b.png)
然后可以排除特定的文件夹名吗
举个例子 cg都是 分 有字和无字分叉的
我都是独立分开文件夹放 如果可以排除 特定名的文件夹 比如无字
![image](https://user-images.githubusercontent.com/30548000/217298020-e5d804e1-e0fb-4b0e-b920-e6b29e8c304e.png)
就不会出现这种双眼皮 的情况了
![image](https://user-images.githubusercontent.com/30548000/217298207-f1880a51-6870-4d83-9ab9-5b3b16378598.png)
因为你能扫到名字 直接用名字排除比路径方便
路径很多。。。 不能挨个写呀
![image](https://user-images.githubusercontent.com/30548000/217299395-11c49e0f-1190-4da6-9f8f-2bc2724ef1fa.png)
以上拙见 不知 开发者大佬可否酌情考虑下

**Comment by lhj5426** [comment]
还有排除了类型 比如我文件夹里有 压缩包也有文件夹
可以设置 排除 掉压缩包 只加载 文件夹 不然还是会出现另类的
压缩包 和 文件夹 的双眼皮

**Comment by SchneeHertz** [comment]
UI以后可能会改
创建时间，或者说修改时间可以加
排除“无字”的文件夹，输入“无字”就可以了，如果还要排除压缩包，“无字|zip|rar”，依此类推，更复杂的建议去看正则表达式的文档

**Comment by lhj5426** [comment]
要是那个 正则框了里 要排除的关键字 
而不是要排除的路径 
我就理解了 写路径 没理解

**Comment by SchneeHertz** [comment]
1.4.8已增加修改时间排序
