### ISSUE TITLE
能设置排除格式么

### ISSUE THREAD

**Issue by lhj5426** [SchneeHertz/exhentai-manga-manager#6]
文件夹里还有压缩包现在连文件夹里的压缩包也读取出来了
尊敬的开发者可以增加一个排除读取格式么 排除压缩包格式 或者排除 特定文件夹名的文件夹

**Comment by SchneeHertz** [comment]
@lhj5426 1.3.7版本已发布，已增加隐藏指定漫画的功能

**Comment by lhj5426** [comment]
> @lhj5426 1.3.7版本已发布，已增加隐藏指定漫画的功能

谢谢你提醒 但是
![image](https://user-images.githubusercontent.com/30548000/174540394-18ddb8eb-0ba7-4ade-9341-3a49eda3bfd4.png)
我好像没发现怎么样yin'c隐藏

**Comment by lhj5426** [comment]
左键没提示 右键也没菜单 设置里也没有填写排除的地方 呜 我麻抓儿了 不知道怎么操作
