### ISSUE TITLE
Option to save search terms in a list

### ISSUE THREAD

**Issue by SaberNight** [SchneeHertz/exhentai-manga-manager#63]
I like some particular artists more than others, but there is no way to quickly access those artists. The collections and bookmarks would have to be maintained with each new work. 

So could you add a button that allows us to save and access specific searches? That way you wouldn't have to type in specific search terms each time and can quickly search your favorite genres.

There doesn't seem to be an OR function built into the search unfortunately, right? On the ehentai page a "~" character is interpreted as OR, so you can display multiple artists at once with one search query.

**Comment by SchneeHertz** [comment]
Do you prefer to save the search history or add a list of options manually

**Comment by SchneeHertz** [comment]
I will implement logical or prefixes, but do not support combinations of prefixes, that is too complicated

**Comment by SaberNight** [comment]
Thank you for your quick reply!
I would prefer a list that you can add manually.

But maybe it would be easier to integrate it into the user interface if you can only save the search term. 
For example with a star icon to "save" the search term and then a star icon to call the saved keyword list.
Here's just an idea of how it might look, in the end I'm happy to see an integration no matter what it looks like. 

https://imgur.com/a/bgd3Fxb

**Comment by SchneeHertz** [comment]
Added customOptions in version 1.4.10.
