### ISSUE TITLE
下一本和随机下一本都无效，还有加载乱序

### ISSUE THREAD

**Issue by zbt000** [SchneeHertz/exhentai-manga-manager#65]
下一本和随机下一本点完没反应
![image](https://user-images.githubusercontent.com/28668512/222943582-79909b8e-93bb-4fe6-bb40-aec99e398738.png)
然后如果在本子A打开但尚未加载完的时候关闭并打开本子B，有概率出现A的页面混在B的里面
更新完版本就这样了，不知道是我的问题还是bug

**Comment by SchneeHertz** [comment]
是bug

**Comment by SchneeHertz** [comment]
1.4.10已修复此问题
