### ISSUE TITLE
我想知道"从sqlite中获取数据时"时。用的是什么进行查询的。

### ISSUE THREAD

**Issue by sohiidayo** [SchneeHertz/exhentai-manga-manager#67]
我写了一个py脚本，用来修改sqlite数据库。
是用于将导出的json中获取titer字段中的gid字段(因为我的压缩包全是以 gid-titer.zip 命名格式的)
之后用查询修改语句修改sqlite中的torrents字段中的hash。没有torrents字段的就创建一个。
在成功运行脚本后，修改了数据库里的和json有关的所有hash值。
但是在从sqlite获取元数据还是失败了。
不是用hash，是其他字段查询的吗( ๑ŏ ﹏ ŏ๑ )

**Comment by SchneeHertz** [comment]
是用压缩包的第一张图片的sha1值与数据库中的thumb字段中的sha1做匹配

**Comment by sohiidayo** [comment]
谢谢，我把它做出来了。现在正在愉快的匹配数据。
