### ISSUE TITLE
有时候它就是获取失败，本地文件名和exhentai上的完全一样，exhentai上也能搜索到，但就是获取失败

### ISSUE THREAD

**Issue by nxoet** [SchneeHertz/exhentai-manga-manager#68]
比如两个本地文件，文件名如下：
[あるぷ] 善い出会い (COMIC BAVEL 2022年2月号) [中国翻訳].zip
[あるぷ] ルーティーン (COMIC BAVEL 2022年10月号) [中国翻訳] [DL版].zip

exhentai上的地址为：
https://exhentai.org/g/2295493/0d3dc43ec9/
https://exhentai.org/g/2314519/3e71142b99/
且文件名完全一样，但在软件里获取就是失败。

点进两文件详情页：
第一个文件，选择“通过文件名获取数据”，搜索不到，将后面的“[中国翻訳]”删除后，能搜索出来。
而第二个文件，不用删减文件名，直接就能搜索到，但就是主页批量获取时，它还是获取不到。

**Comment by SchneeHertz** [comment]
默认不是通过文件名获取的，如果是直接从E站下载的压缩包，一般是能匹配到元数据的
