### ISSUE TITLE
无法记录上次阅读的位置，每次打开软件都要重新扫描整本漫画的页数

### ISSUE THREAD

**Issue by qw853286543** [SchneeHertz/exhentai-manga-manager#69]
**Before giving feedback on a bug, please make sure that what you are giving feedback on is not explained in the wiki**
每次打开软件随便点开一本看过的漫画阅读
它都会重新开始扫描页数
这本漫画我之前已经扫描过了
关闭软件后再打开，还是会重新扫描

如果能记录下已添加漫画页数和上次关闭前的观看位置就好了
**Question**
Describe the problem you are experiencing and the result you expect

**Comment by SchneeHertz** [comment]
1.5.3已更新相关功能
