### ISSUE TITLE
合集或者收藏能否批量添加

### ISSUE THREAD

**Issue by ququguoguo** [SchneeHertz/exhentai-manga-manager#7]
我把本子按照收藏下载到了不同的文件夹，大约1.5w个本子
![图片](https://user-images.githubusercontent.com/107012178/173877288-891b3808-a76c-47c0-8443-8b37b6bdee70.png)
怎样实现在合集或者收藏内区分呢
![图片](https://user-images.githubusercontent.com/107012178/173877527-4a585287-da27-410c-9780-5c2ee1c4c2b8.png)

**Comment by SchneeHertz** [comment]
下个版本我把文件路径加到搜索内容里，你可以用搜索定位到某个文件夹内的漫画

**Comment by SchneeHertz** [comment]
@ququguoguo 1.3.7已发布，可以搜索文件路径的片段
