### ISSUE TITLE
从Sqlite导入的标签的排序有问题

### ISSUE THREAD

**Issue by MIllI0N-IllUSI0N** [SchneeHertz/exhentai-manga-manager#72]
14.10版本，同一本漫画，联网获取数据得到的标签是这样的：
![1](https://user-images.githubusercontent.com/124518058/230680143-deffd804-9885-4188-88ec-920503a61f73.png)
用本地的api_dump.sqlite导入数据，得到的标签顺序不一样：
![2](https://user-images.githubusercontent.com/124518058/230680197-cbd2873d-1a0f-47ba-979d-a4be69573e0b.png)
修复本地元数据，去掉了空白标签但顺序依旧不一样：
![3](https://user-images.githubusercontent.com/124518058/230680434-837ab975-a4e5-48be-86ac-227f131b854c.png)
能不能把它们统一一下？（话说为啥这里只有category这一项是中文）

题外话，我在1.4.7版本通过sqlite导入了很多漫画的数据，这些漫画在之后遇到了不显示大小跟修改日期的问题：
![5](https://user-images.githubusercontent.com/124518058/230681961-7af970c3-fb91-4449-a9c9-92f6e7414c58.png)
我当时以为是什么小bug没去管，最近无聊点了一下“修复本地元数据”后发现能正常显示了。
(挠头.gif) 这也没人告诉我要这么做啊！更新说明没写，wiki上关于从sqlite导入的部分是这样说的“如果库扫描是在更新到1.4.0之前，需要先执行修补本地元数据”

**Comment by SchneeHertz** [comment]
导入sqlite那里的tag顺序没有排好，之后调整一下
category是中文因为它不是tag，而是漫画的其他信息，所以随软件语言的更改而变化
修改时间和文件夹大小是1.4.8加上的，之前扫描的会缺这个字段，不过我忘记在release里说明了呵呵

**Comment by pikawindy** [comment]
借地方问下，从Sqlite导入数据后，是再点击“批量获取EX元数据”元数据吗？怎么感觉我新建库后，获取的还是联网的数据，而不是api_dump.sqlite导入的数据？

**Comment by SchneeHertz** [comment]
sqlite数据库里只有部分漫画的元数据，比较新的还要联网获取。

**Comment by SchneeHertz** [comment]
Update is in version 1.4.11
