### ISSUE TITLE
封面丢失

### ISSUE THREAD

**Issue by pikawindy** [SchneeHertz/exhentai-manga-manager#73]
今天手动扫描后增加的本子没封面，但之前的是有的。然后我试过重启软件和电脑都还是这样，应该不关梯子的事？因为我能正常获取元数据，只是封面没了。

系统：win11
软件版本：1.4.10
本子都是zip格式
![剪贴板图片](https://user-images.githubusercontent.com/63467634/230718793-fe569a6a-242a-464d-85f8-4b48b6193bb8.jpg)

**Comment by SchneeHertz** [comment]
试一下运行一次设置-高级-修补本地元数据

**Comment by pikawindy** [comment]
> 试一下运行一次设置-高级-修补本地元数据

这修补也太慢了，修补完原先有的封面也没了。。。。

**Comment by pikawindy** [comment]
> > 试一下运行一次设置-高级-修补本地元数据
> 
> 这修补也太慢了，修补完原先有的封面也没了。。。。

好吧，再修补多次就好了
