### ISSUE TITLE
支持条漫

### ISSUE THREAD

**Issue by Smile8848** [SchneeHertz/exhentai-manga-manager#74]
能支持下条漫就好了，现在似乎是每页底下都有东西
另外能支持下右键移动文件吗？这样看完之后就能移到别的位置。

**Comment by SchneeHertz** [comment]
需要什么特别的点来支持条漫吗？
移动文件的功能目前还没打算做。

**Comment by Smile8848** [comment]
> 需要什么特别的点来支持条漫吗？ 移动文件的功能目前还没打算做。

自带阅读器每页下面会有页码然后条漫会被分隔开..

**Comment by SchneeHertz** [comment]
Update is in version 1.4.11
