### ISSUE TITLE
有办法离线自定义和编辑tag吗？

### ISSUE THREAD

**Issue by HPFAIZ** [SchneeHertz/exhentai-manga-manager#75]
因为想作为管理软件，不想使用ex或eh的元数据。
想本地编辑tag。我看到一个搜索本地的按钮，但是不清楚怎么用

**Comment by SchneeHertz** [comment]
导入漫画文件后，点开进入详情页，有个编辑标签的按钮

**Comment by HPFAIZ** [comment]
编辑标签然后增加类别那一项叭。那个要怎么保存标签啊，每次再点开标签总会消失

**Comment by SchneeHertz** [comment]
还是在原来的位置，点显示标签就保存了

**Comment by HPFAIZ** [comment]
大佬您看看？
https://pan.baidu.com/s/1KV0ndwGm8AVb6iwj_AvzNw?pwd=624j

**Comment by SchneeHertz** [comment]
> 大佬您看看？ https://pan.baidu.com/s/1KV0ndwGm8AVb6iwj_AvzNw?pwd=624j

你加完类别后要加标签阿

**Comment by HPFAIZ** [comment]
啊啊啊啊啊 懂了 感谢！
