### ISSUE TITLE
下一本和随机下一本都无效

### ISSUE THREAD

**Issue by zbt000** [SchneeHertz/exhentai-manga-manager#76]
版本1.4.10
点击下一本或随机下一本只会变灰
![image](https://github.com/SchneeHertz/exhentai-manga-manager/assets/28668512/93c1cb6a-4338-46c0-ae74-e3072c008735)

**Comment by SchneeHertz** [comment]
看一下roaming/exhentai-manga-manager或者程序目录下log.txt的内容

**Comment by zbt000** [comment]
roaming里面的log.txt是空白的，不知道是不是我卸载重装过的原因，但我开了几个本子关了，还是空白的

**Comment by zbt000** [comment]
> 看一下roaming/exhentai-manga-manager或者程序目录下log.txt的内容

roaming里面的log.txt是空白的，不知道是不是我卸载重装过的原因，但我开了几个本子关了，还是空白的

**Comment by SchneeHertz** [comment]
那在操作后，按Ctrl+shift+i，看console页的输出

**Comment by zbt000** [comment]
出现如图所示错误，多次点击次数累加
![image](https://github.com/SchneeHertz/exhentai-manga-manager/assets/28668512/e3a09917-d92c-4182-a229-1d773d33eed2)
关闭当前画廊时会报另一如图错误
![image](https://github.com/SchneeHertz/exhentai-manga-manager/assets/28668512/ef23a4a7-3bca-4aa
[图一.txt](https://github.com/SchneeHertz/exhentai-manga-manager/files/11833765/default.txt)
1-86c0-768b8efe1c8f)
[图二.txt](https://github.com/SchneeHertz/exhentai-manga-manager/files/11833766/default.txt)

**Comment by SchneeHertz** [comment]
是不是打开的是合集内的漫画，你试下打开软件后直接点主页上第一本漫画的‘读’按钮，再试试这个功能

**Comment by zbt000** [comment]
> 是不是打开的是合集内的漫画，你试下打开软件后直接点主页上第一本漫画的‘读’按钮，再试试这个功能

依旧出现如图错误，其中的前两项是打开前就存在的，后两项是点击下一本与随机下一本出现的
![image](https://github.com/SchneeHertz/exhentai-manga-manager/assets/28668512/3529618b-4e8a-4991-8f03-babd0be63532)

**Comment by SchneeHertz** [comment]
我这边复现不了这个问题，其他使用者也没反馈过类似的问题，你使用的环境或者管理的漫画有什么比较特别的吗

**Comment by zbt000** [comment]
> 我这边复现不了这个问题，其他使用者也没反馈过类似的问题，你使用的环境或者管理的漫画有什么比较特别的吗

没啊，我也很疑惑，我再重装试试吧

**Comment by zbt000** [comment]
> 我这边复现不了这个问题，其他使用者也没反馈过类似的问题，你使用的环境或者管理的漫画有什么比较特别的吗

我已经无奈了，我尝试了下绿色版，清理appdata里面的exhentai manger文件夹，删掉所有相关注册表项，还是无法点下一本
环境就是普通win11环境，漫画也没什么特殊

**Comment by SchneeHertz** [comment]
> > 我这边复现不了这个问题，其他使用者也没反馈过类似的问题，你使用的环境或者管理的漫画有什么比较特别的吗
> 
> 我已经无奈了，我尝试了下绿色版，清理appdata里面的exhentai manger文件夹，删掉所有相关注册表项，还是无法点下一本 环境就是普通win11环境，漫画也没什么特殊 又尝试了一下，在单页和双页模式下都是可以下一本的，但卷轴模式不行


卷轴模式下的下一本确实有问题，下个版本我会修复

**Comment by SchneeHertz** [comment]
Update is in version 1.4.11
