### ISSUE TITLE
内置阅读器无限loading

### ISSUE THREAD

**Issue by pikawindy** [SchneeHertz/exhentai-manga-manager#77]
系统win11，软件1.4.10

有些压缩包用内置阅读器打开会卡在loading，点其他按钮没反应，只能点关闭重开软件。
这些打不开的压缩包我看了下，体积也就二三十m，都是zip格式

其实一般我是很少用内置阅读器，但有些封面自动识别成汉化组的宣传页，不得不用内置指定封面

**Comment by SchneeHertz** [comment]
方便的话传个出错的包我测试一下

**Comment by pikawindy** [comment]
[(CSP6) [PROJECTハラキリ (介錯)] ニセニセ○イ5.5 (ニセコイ) [英訳].zip](https://github.com/SchneeHertz/exhentai-manga-manager/files/11866418/CSP6.PROJECT.5.5.zip)

**Comment by SchneeHertz** [comment]
我测试了这个压缩包，没有发现问题
你可以试着改一下出错的压缩包的文件名，去掉特殊符号再试试，这个软件使用的一些三方库对特殊符号的处理不太完美。
