### ISSUE TITLE
建議支援從chaika.moe獲取標籤

### ISSUE THREAD

**Issue by bennyz327** [SchneeHertz/exhentai-manga-manager#78]
如題，不知道以前有沒有人提過

這是一個收集範圍包括但不限於 "E站中被版權砲的作品" 的檔案和meta資料的備份站
近期發現，常常一個本子要獲取元數據的時候E站已經下架該作品了

希望能在E站無法獲取標籤的時候，自動尋找 (或手動貼上) 對應的chaika網址之後解析標籤和作品meta

網址:
https + panda.chaika.moe

**Comment by SchneeHertz** [comment]
Update is in version 1.4.11
