### ISSUE TITLE
希望能增加一个通过识别文件名自动把作者团队语言之类的标签直接标上去的功能

### ISSUE THREAD

**Issue by dudulu23** [SchneeHertz/exhentai-manga-manager#81]
一般e站下载的文件名都是（c100）[团队名( 作者名)]  作品名  这种格式，exhviewer下载的文件名格式前面会加上    编号-，通过直接解析文件名就能得到作者和作品名然后直接修改meta，lanraragi上有个叫chinesemeta插件就有这样的功能，另外希望有一个标签同步的功能，比如同一个作者会有罗马音和日文两个不同的标签，搜索日文名时同时把罗马音的结果也搜出来，

**Comment by SchneeHertz** [comment]
元数据用的是漫画文件关联到的eh的画廊的元数据，暂时不考虑从文件名获取
搜索时会同时搜索标签和文件名，文件路径，元数据本身是不包含英文以外的语言的
