### ISSUE TITLE
当库里漫画数量过多时，对漫画的“添加/移除收藏”操作需要等上一段时间才会真正生效

### ISSUE THREAD

**Issue by MIllI0N-IllUSI0N** [SchneeHertz/exhentai-manga-manager#83]
试了一下，当库数量超过1K的时候，“收藏”操作差不多要等2秒才能完成。点击收藏后，虽然软件内立刻显示为已收藏的状态，但只要在这期间关闭软件，则会丢失这次收藏。

**Comment by SchneeHertz** [comment]
这是因为目前使用json文件保存漫画的数据，写入硬盘这个操作延迟稍微大了些
下个大版本会改用sqlite存储数据，不过那是之后的事情了
