### ISSUE TITLE
“导入元数据/从sqlite导入”的提示有误

### ISSUE THREAD

**Issue by MIllI0N-IllUSI0N** [SchneeHertz/exhentai-manga-manager#84]
应该是个老bug了。点击“导入元数据/从sqlite导入”这两个选项后，不选择任何文件，直接关闭弹出的资源管理器，软件内也会提示导入成功（好像还会真的执行导入成功后的操作）

**Comment by SchneeHertz** [comment]
之后修一下（这个不修也没关系吧）
