### ISSUE TITLE
从剪贴板黏贴信息这个功能能直接添加作品名和网址的信息吗？

### ISSUE THREAD

**Issue by dudulu23** [SchneeHertz/exhentai-manga-manager#87]
因为网络的问题我无法直接获得e站的元信息，所以想通过一些脚本从其他渠道获得字符串从剪贴板黏贴输入元信息。我尝试了一下复制标签的功能，只能提取出tag信息，没有作品名和网址。是否有途径能通过字符串来直接添加作品名和网址

**Comment by SchneeHertz** [comment]
复制粘贴功能设计出来是为了在软件中不同漫画间转移元数据用的，故没有包括作品名和网址
不过粘贴是支持除了tag之外的其他字段的，你可以参考以下的json结构：
```
{
    "title": "[Pixiv] 栞しい (12450448)",
    "coverPath": "C:\\Users\\seldon\\AppData\\Roaming\\exhentai-manga-manager\\cover\\uCE9XkYb7lZpsf41zPzd7.webp",
    "hash": "1fba7f0ef757ee37a40dfb46ca1a8b57ccb65262",
    "filepath": "C:\\Users\\seldon\\Pictures\\Comic\\[Pixiv] 栞しい (12450448).zip",
    "type": "zip",
    "id": "Qq6X-iHHphPvY9hr91GEh",
    "pageCount": 72,
    "bundleSize": 234958203,
    "mtime": "2023-07-24T08:58:32.147Z",
    "coverHash": "bd52e56cec79e747ae9d3c404ca02bb6586e34f3",
    "status": "tagged",
    "date": 1690857820370,
    "rating": 3.98,
    "tags": {
      "female": [
        "maid"
      ],
      "other": [
        "non-h imageset"
      ]
    },
    "title_jpn": "[Pixiv] 栞しい (12450448)",
    "filecount": 72,
    "posted": 1687707595,
    "filesize": 238190628,
    "category": "Non-H",
    "url": "https://exhentai.org/g/2591279/abd599b5ca/"
  }
```

**Comment by SchneeHertz** [comment]
从ex页面复制出元数据的脚本，可能其他人也用得到，你有没有打算把这个脚本共享出来？

**Comment by dudulu23** [comment]
感谢，我按照这个格式写了简单的脚本   [https://github.com/dudulu23/exhentai-metascript/blob/main/exhentai-metascript.user.js]

**Comment by SchneeHertz** [comment]
> 感谢，我按照这个格式写了简单的脚本 [地址](https://github.com/dudulu23/exhentai-metascript/blob/main/exhentai-metascript.user.js)

你的脚本有几处问题：
1. 元数据中的mtime指的是漫画文件的修改时间，ex的页面显示的时间是上传时间，对应的是posted，格式是以秒为单位的时间戳，整数
2. rating是浮点数
3. title的id值与ex页面不一致，我推测是你使用的其他脚本修改了页面上title的id值

我进行了一些修改后，发现这个脚本和EhSyringe不兼容，我用不了，索性重新写了个，也给你参考下：
[提取e-hentai画廊元数据](https://sleazyfork.org/zh-CN/scripts/472321-%E6%8F%90%E5%8F%96e-hentai%E7%94%BB%E5%BB%8A%E5%85%83%E6%95%B0%E6%8D%AE)
