### ISSUE TITLE
v1.5.0 有时候打开软件时不显示任何漫画

### ISSUE THREAD

**Issue by MIllI0N-IllUSI0N** [SchneeHertz/exhentai-manga-manager#89]
就跟第一次打开软件时一样，设置都在，但是软件内没有任何内容，点开左边的库显示“暂无数据”
这bug似乎是概率性触发的，我进行的是这么一个操作循环：
打开软件，添加/移除收藏（有时候是跳过的这步），关闭软件，打开软件……其中两个操作间的间隔不超过2秒，在重启软件时，有几率触发这个bug；
触发bug后，操作就变成了：
关闭软件，打开软件-检查是否正常，不正常-关闭软件，打开软件……有时候它会一直卡在这个bug上，重启N次后又好了。

**Comment by SchneeHertz** [comment]
出现问题时，按Ctrl+Shift+I打开Devtool，Console是否有显示错误信息，Roaming/exhentai-manga-manager文件夹内的log.txt内是否有显示错误信息？

**Comment by SchneeHertz** [comment]
> 不知道你有没有用过Windows的硬链接（可以快速生成多份复制件且不占用额外空间），可以试试这样创建一个测试环境： 1、安装这个[link shell extension](https://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html#Download)，安装完可以能要重启一下资源管理器 2、任意盘符新建一个test文件夹，放一个非压缩包漫画A到里面 3、在test文件夹里，用右键拖放漫画A到同文件夹的空白位置，松开右键，创建链接点-硬链接副本 4、创建完后现在有2个漫画A了，继续对这2个漫画A进行第三步操作，直到创建出1024个漫画A 5、打开emm将test设为库，进行测试 不用了的时候按shift+delete删掉整个test文件夹就行

谢谢，这个很有用

**Comment by SchneeHertz** [comment]
如果关闭软件后，等一段时间（30秒），再打开软件，还会出现这个问题吗？

**Comment by SchneeHertz** [comment]
我找到原因了，读取数据库和更新数据库结构的命令同时执行导致的冲突，我明天会发布1.5.1修复这个问题。
临时的解决方案是打开软件后按Ctrl+R重新载入或者手动扫描
