### ISSUE TITLE
Ctrl++快捷键无效

### ISSUE THREAD

**Issue by MIllI0N-IllUSI0N** [SchneeHertz/exhentai-manga-manager#91]
另外应该把alt出菜单的这个功能写进Wiki

**Comment by SchneeHertz** [comment]
如果你用的不是全键盘的话，数字区的加号是要加上Shift的
搜索栏的快捷键参考的是chrome的地址栏的快捷键，Ctrl+L和F6

**Comment by SchneeHertz** [comment]
我之后改成Ctrl+=好了，这里怎么改都会有点不对劲
