### ISSUE TITLE
V1.5.1 启动软件时看不见窗口，但是在任务管理器中却有进程

### ISSUE THREAD

**Issue by Lezy233** [SchneeHertz/exhentai-manga-manager#93]
V1.5.1更新后启动软件时看不见窗口，但是在任务管理器中却有进程

**Comment by Lezy233** [comment]
另外好像不支持.png格式的图片

**Comment by SchneeHertz** [comment]
Roaming/exhentai-manga-manager文件夹内的log.txt内是否有显示错误信息？
png是支持的

**Comment by Lezy233** [comment]
没有错误信息，是一个空的txt文件

**Comment by SchneeHertz** [comment]
你kill掉已有的进程再试试

**Comment by Lezy233** [comment]
我卸载后重新下回了v1.4.11版本，可以正常启动
卸载再次安装v1.5.1，发现仍然没有窗口。
同时我发现v1.5.1每次打开软件的时候后台会有两个程序进程

**Comment by SchneeHertz** [comment]
一般是4个进程
中断是指大图的一部分不显示吗，还是之后的图片都不显示了

**Comment by Lezy233** [comment]
之后的图片都没法显示

**Comment by Lezy233** [comment]
成功了，我把Roaming/exhentai-manga-manager文件夹全部删除后重新下载，又可以正常启动了
