### ISSUE TITLE
增加标签预搜索列表

### ISSUE THREAD

**Issue by tianhefanxing** [SchneeHertz/exhentai-manga-manager#95]
当漫画在合集里面的时候，是无法被搜索栏搜索到的，而且一本漫画无法放入多个合集内，可否设立标签列表，放置于搜索框边，方便随时搜索预设的漫画标签（作者，类型等）。
随有预定义搜索项，但放置于下拉搜索框内，使用有些不便，能否单独放出，方便检索。

**Comment by SchneeHertz** [comment]
在合集内的漫画，如果符合搜索条件，会以合集的形式显示在搜索结果中
你可以将合集理解为文件管理器中的文件夹，如果需要对一本漫画做多个所属的标记，我建议用自定义的标签
预定义的搜索项现在有哪些不方便的地方，可以详细说一下吗，我不觉得单独做一个组件会更加方便。
