### ISSUE TITLE
与网页的联动的脚本

### ISSUE THREAD

**Issue by dudulu23** [SchneeHertz/exhentai-manga-manager#98]
查询database.sqlite利用网页脚本把本地已有的漫画直接标记在网页上。
我这边用了php来解析database.sqlite，然后再用js脚本修改了网页来显示这本漫画在本地有没有
https://github.com/dudulu23/exhentai-manga-manager-script
作者有没有兴趣加入这个功能

**Comment by SchneeHertz** [comment]
这个功能感觉有些人会用到，但我目前没有增加这个功能的计划
